<a href="https://colab.research.google.com/github/csmith3051/HU-DS-Bootcamp/blob/main/Ghana_Census_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Research Question

**"How does access to post-secondary education make a positive impact career prospects in Ghana?"**

# Problem Statement

With the increasing development of services and technology globally, higher education attainment has shown in many studies to correlate to employability and higher salaries. As the services growth rate continues to increase in Ghana, it is pertinent for Ghanaian youth to have access to quality education and skills training to increase their socio-economic status as country focuses more on white collar professional roles and less on agrarian labor. Our research aims to understand how does access to post-secondary education make a positive impact career prospects in Ghana?

# References

1. [Higher Education and Labour Market Situation in Ghana: A Case Study of the Relationship between University Education, Labour Market and Government Policies](https://efaidnbmnnnibpcajpcglclefindmkaj/http://www.fondazioneedu.org/wp-content/uploads/2020/03/Ricerca-CDD.pdf) (2020)
2. [A Descriptive Assessment of Higher Education Access, Participation, Equity, and Disparity in Ghana](https://journals.sagepub.com/doi/epub/10.1177/2158244013497725) (2013)
3.[Ghana Statistical Service Official Website](https://www.statsghana.gov.gh/)
4. [Students' Career Aspirations and Pedagogical Experiences in Ghanaian Universities](https://ppl-ai-file-upload.s3.amazonaws.com/web/direct-files/attachments/54255874/d7e9e171-524a-4d45-a0ec-98abb5d9fbbf/Students-Career-Aspirations-and-Pedagogical-Experiences-in-Ghanaian-Universities.pdf?AWSAccessKeyId=ASIA2F3EMEYETMY7K6AA&Signature=ZuYRrjbgCCJGIORza%2FbANpDDErw%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEK7%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJIMEYCIQDeERAGdv6e78gZpWSyLFau404FByHVThykGx4qa3uBPgIhAOM0L1Yl%2F5XQ%2FblBQ7sOVPl%2BjjCEMmVjY2QsLmAQmCkwKvoECJf%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQARoMNjk5NzUzMzA5NzA1Igwx9aomBtwkNObN%2B9sqzgQlwQrfE1C2jwfvULYE9RFCjfhCix4HjbGINxqroOWyB4LCAjUNhDUd%2FdjvhaMQ5NtXzHJqj3FipFb12BjGQctNwnyGQO0pjnV183JR93EXds0OD0krNWe5NA4PrBm2MpH1qO3d7BdqyuyLdLSI8BLEbUbvDkrOFR35UmPgBe1%2BTNr1b2nmIMuiqxp5hBD8zomF4g6QbUGzSobYBoVzqvViMsF6mXY6qfnKZHPg29hElnww0WJAnFQa6A9gu9TCxRfUyfV345uP%2FSIDXKo9cQlv3fGq%2BUF4082aX%2BGF56869tvSiDGeolPdwEFx%2FHPV%2FL3YQ9VkWMJjx5OkziFTy2KGR%2Bc%2Bz8KvW%2FF6cR23%2FecVTT2JOui2%2FEa2vR70fEcRZgTQvUFZhLLtfCMhFEBM7WycIXR98M%2BIZJL4GzANVpOnfE5VsFcC8io1d90ey9EMC4jadWGl5kGX%2FBViffpMZD6xeNIYIURVqah6mVqJIo3XRaqF0Pvw%2BCCkL5%2B6iPm7RMEdhww4Q6v0HrXUA4EHViIxWMpry0thmQE0nRN5ayxSW5YVULLintdyfAV3YNihDzIw3%2F9VdvisF9UeV%2BwiiR2UYOkfACuOGETRGDHxcHLAj%2FogevGx01sNaS7qVBgCBGvLi4NNsc6nzr5Byd6v6dBWVyJdpgel0t2YPEvxhH4o8oL52PXQS%2BKoGgANUjT5MtrxoGeBwum%2BwTN6XwyvTbJYzQNdPqG1s0eMHWEG6h63ACMDObWGrde359Ikuv0L6H4H5fuKHXqmBL%2F8C1pEqzC84MzCBjqZAXK2InZJyagb0vmrCrdncRp0tap3nbO3sRMoqI4moP2uqOeGYM3kwsgq%2FwhpKws%2FvvqAKA5%2FENUDaHhl92Mm7lMVTipuPEk7oT6Q4tC3tyugqykHTcxq82hToVPJhjYMJxRjmjER75kc2oWFOyFGTZ0emDsJOtM3RXHLgTxVknqgM8r7RTKCY7fiaQjL9WYJXoUlmwjrCd8qog%3D%3D&Expires=1750282878) (2022)
5. [Private Returns on Education in Ghana: Estimating the Effects of Education on Employability in Ghana](https://ppl-ai-file-upload.s3.amazonaws.com/web/direct-files/attachments/54255874/9f8742fc-83ed-43f6-8202-b849636387e9/ajol-file-journals_137_articles_87629_submission_proof_87629-1633-217100-1-10-20130422.pdf?AWSAccessKeyId=ASIA2F3EMEYEWMMSTBRK&Signature=ju0%2FqPa7pvClRfpdynAZVKj17h0%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEK3%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCIADeogO9p%2BiVa32MEgNgV7w2YVpx3aUZP8hq8TxRO4STAiEApCouU6WdYFVejOnIH1IS0SF83kWQgWSYpZtycREXs9Uq%2BgQIlv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARABGgw2OTk3NTMzMDk3MDUiDPrI1tBKV%2FLXGRDzDirOBERfobcOy5zZNT1FANQlc6hwVYT0W8kdJ3PvJdF6wv9HQToH9v2hzBRqgDd4XvKae22ZyxhtZZeiTo4U8vF%2FOyo%2Bll6SsPfq5T8KW7CF9Q326KyKdNnOXWqwE1R7xCctfd1ehDZLgi3%2BtP5plxM15FbsaNQH8%2BNxxsERcqN9fXOKQz9t9P9Wn6Z%2FzhqfbPIpQf8VUwTTeSfFOiXsJ5270D5D19xdaQNWDZuzDKk%2FiREN2WCFXhSL6ZyW8XYIsSCd5LsH5qJqy02bIcbxdlypiZ8L6RjgPzt9%2Fm1xMnGlEFd%2B%2FsacT72W%2FlG6%2FBKKVR3Tibj0DGxnZ%2FXomJWcSgmfMQgDyNk5chWjdLXqhX6IvhNHzpLMm0I3Bi0GzbAf6hVZqcgHVfwtFBgImAW23hhde%2F8qmoSLbyDTgUjLamiYC%2Fzf3pYaQvAClvXHRVMtKQMakmVUWf96ZF3nD5gQpUQVVk9N2U%2BTo4oFm9vYE0m2pTE8dmuO8crhju67faOPFCcDsvuFNpmCYXGq2HZK9NzbvzyOr020lZ1onlXRVDNY%2FMJMEL%2FuV7hmRts5n%2Fo7Rthy9l6BiOIGGziwKwAvkVaE2E8tCsQTk7d1yXwWiw14bG3Y36h3yks1q7fXEaOPJmevMqrSkNeSPQM2F1nLtWx%2BXFNTVBvU7u6zRisBn2e1VKMUcTqJvci4R1vd85%2FuLWW10NKFD%2Bj4Rq4xflWnvP8WttIXfJNW%2BXjevh%2BXhcsngIi37Q1IFu6fLgBh9HPj2ZA%2BFoXDyBkQOENs4PiHkRyLMJbOzMIGOpoB0Gqd%2F1yDpIkrYUM95PVh1aRRp66XDQ9qWMc%2BF%2BfWIHR9k2hJCrT7NHjM2FtqABaOM2Vu5OuFz6O1t0pufwBJt09yIZbUq3RTK3YetvTtrI2AGJRJeZc3Axy1B8MNO6WnUa8%2B0OTy5nzQvHLSaHbFI2KFXg%2BhKpDKyupdKZ1ESrWJUQFQ0AGdjnUx1CD57MANEs0QY9mGSppzQA%3D%3D&Expires=1750282273) (2012)

In [69]:
# Import the libraries
import numpy as np                  # Scientific Computing
import pandas as pd                 # Data Analysis
import matplotlib.pyplot as plt     # Plotting
import seaborn as sns               # Statistical Data Visualization

# Let's make sure pandas returns all the rows and columns for the dataframe
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Force pandas to display full numbers instead of scientific notation
# pd.options.display.float_format = '{:.0f}'.format

In [70]:
!git clone https://github.com/laketalkemp/2025-HUDS-Bootcamp.git

fatal: destination path '2025-HUDS-Bootcamp' already exists and is not an empty directory.

In [71]:
!pip install pyreadstat

Requirement already satisfied: pyreadstat in /usr/local/lib/python3.11/dist-packages (1.2.9)
Requirement already satisfied: pandas>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from pyreadstat) (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2.0->pyreadstat) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2.0->pyreadstat) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2.0->pyreadstat) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2.0->pyreadstat) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.2.0->pyreadstat) (1.17.0)

In [72]:
import glob

# List all Stata files in the directory
dta_files = glob.glob('2025-HUDS-Bootcamp/Data/THREADS/Wave_3/*.dta')
print(dta_files)

['2025-HUDS-Bootcamp/Data/THREADS/Wave_3/06g_past12months.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/10aix_public_services.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/open_ended.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/02a_nr_relatives_roster.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/11d_fuelconsumptionquestions.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/01fi_employmentmain.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/01gii_edcareer.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/04o_cropsalesstoresquestions.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/11c_otheritems.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/01fii_employmentsecondary.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/01eiii_math.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/04o_cropsalesstoresservices.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/01giv_education_beliefs_pre.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/07c_ids_roster.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/02a_nr_relatives_questions.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/commtype.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/12a_housingcharacteristics1iii_structure.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/10avi_timeuseloop.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/10di_binteractionsquestions.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/02b_nr_spouses_preroster.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/07a_fertility.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/01d_background.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/04l_inputs.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/01ei_ravens.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/07c_ids_module.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/10c_socialnetworkingquestions.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/05_bizsection.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/09b_education_beliefs_post.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/04nn_gatheringquestions.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/03bii_lendingquestions.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/10avii_financial_health.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/02a_nr_relatives_preroster.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/04l_chemquestions.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/06a_insurance.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/10av_trust.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/10bii_riskpreferences.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/03ai_animalquestions.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/03biv_intransfersquestions.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/08a_reprohealth.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/02b_nr_spouses_roster.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/10aii_subjectivesocialwelfare.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/03bia_borrowingquestions.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/07b_power.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/09a_youngchildhealth.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/03bvi_mobile_money_agents.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/03bvi_mobile_money_accounts.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/05bi_allemployees.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/03aiii_durablegoodquestions.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/10diii_volunteer_questions.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/12a_measurements.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/03biii_outtransfersquestions.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/01gi_generaleducation.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/03bv_savingquestions.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/10aiv_townsend.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/03bi_borrowingquestions.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/05ai_basicinfo.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/12a_housingcharacteristics1ii_utilities.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/01fa_employmentscreener.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/01ev_digitspan.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/12b_housingcharacteristics2.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/03ai_animalquestions_osp.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/06d_dailyliving.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/06c_immunization.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/04h_agsection.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/06e_miscellaneous.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/04i_landtenure.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/03aii_toolquestions_osp.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/01evi_english.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/03aii_toolquestions.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/02b_nr_spouses_newroster.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/01b2_roster.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/01giii_literacy.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/01hii_migrationhistory.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/01eii_fluency.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/00_hh_info.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/10_determine_respondents.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/04k_seedquestions.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/06f_past2weeks.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/05aii_assetquestions_osp.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/05aii_assetquestions.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/04_plotroster.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/02a_nr_relatives_newroster.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/01eiv_nepsy.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/01a_consent.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/10dii_mediaextensionsquestions.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/02b_nr_spouses_questions.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/12a_housingcharacteristics1i_rent.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/03biv_intransfersquestions_org.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/04m_aglabourquestions.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/01b2_newroster.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/10ai_depression.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/01evii_anthropometry.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/04n_harvestquestions.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/01hi_immigration.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/04j_tracploughuse.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/01b2_preroster.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/03bvi_mobile_money_awareness.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/10avi_careforkids.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/05bii_fourimportantquestions.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/03aiii_durablegoodquestions_osp.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/11b_clothingquestions.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/11a_foodconsumption_give.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/08b_power.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/01eviii_consumption.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/01fiii_unemployed.dta', '2025-HUDS-Bootcamp/Data/THREADS/Wave_3/12a_measure.dta']

In [73]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [74]:
import pandas as pd
df = pd.read_stata('2025-HUDS-Bootcamp/Data/THREADS/Wave_3/00_hh_info.dta')
df.head(30)
df.tail(30)

,FPrimary,round,remnant,FPrimary_original,hhmid_original,moved,last_wave,r_code,region
5639,204118029,Split off,No,104118029,2.0,NaN,NaN,3,Greater Accra Region
5640,309312031,Split off,No,109312031,9.0,NaN,NaN,9,Upper East Region
5641,307244093,Split off,No,107244093,8.0,NaN,NaN,7,Brong Ahafo Region
5642,202048039,Split off,No,102048039,5.0,NaN,NaN,2,Central Region
5643,201021062,Split off,No,101021062,4.0,NaN,NaN,1,Western Region
5644,407255040,Split off,No,107255040,5.0,NaN,NaN,1,Western Region
5645,201022018,Split off,No,101022018,5.0,NaN,NaN,1,Western Region
5646,207244010,Split off,No,107244010,5.0,NaN,NaN,6,Ashanti Region
5647,209321034,Split off,No,109321034,4.0,NaN,NaN,9,Upper East Region
5648,201010132,Split off,No,101010132,1.0,NaN,NaN,4,Volta Region
5649,201024038,Split off,No,101024038,6.0,NaN,NaN,7,Brong Ahafo Region
5650,208273063,Split off,No,108273063,6.0,NaN,NaN,10,Upper West Region
5651,309317081,Split off,No,109317081,5.0,NaN,NaN,8,Northern Region
5652,1008308001,Split off,No,108308001,16.0,NaN,NaN,8,Northern Region
5653,201028015,Split off,No,101028015,3.0,NaN,NaN,1,Western Region
5654,206223035,Split off,No,106223035,3.0,NaN,NaN,3,Greater Accra Region
5655,309314012,Split off,No,109314012,4.0,NaN,NaN,9,Upper East Region
5656,208287016,Split off,No,108287016,4.0,NaN,NaN,7,Brong Ahafo Region
5657,208289031,Split off,No,108289031,3.0,NaN,NaN,8,Northern Region
5658,208284006,Split off,No,108284006,3.0,NaN,NaN,8,Northern Region
5659,308282015,Split off,No,108282015,16.0,NaN,NaN,8,Northern Region
5660,408297013,Split off,No,108297013,3.0,NaN,NaN,8,Northern Region
5661,102054060,Main,No,,NaN,Yes,2.0,2,Central Region
5662,206208059,Main,No,,NaN,NaN,NaN,9,Upper East Region
5663,301022018,Split off,No,101022018,7.0,NaN,NaN,2,Central Region
5664,102060014,Main,No,,NaN,Yes,2.0,2,Central Region
5665,208302004,Main,No,,NaN,Yes,2.0,8,Northern Region
5666,107244038,Main,No,,NaN,Yes,2.0,7,Brong Ahafo Region
5667,101003015,Wholly moved,No,,NaN,Yes,1.0,1,Western Region
5668,109320028,Main,No,,NaN,NaN,NaN,9,Upper East Region

# Variables

In [75]:
import pandas as pd
df_eng = pd.read_stata('/content/drive/MyDrive/Ghana Wav 3 Files/01evi_english.dta')
df_math = pd.read_stata('/content/drive/MyDrive/Ghana Wav 3 Files/01eiii_math.dta')
df_unemployed = pd.read_stata('/content/drive/MyDrive/Ghana Wav 3 Files/01fiii_unemployed.dta')
df_gen_ed = pd.read_stata('/content/drive/MyDrive/Ghana Wav 3 Files/01gi_generaleducation.dta')
df_ed_career = pd.read_stata('/content/drive/MyDrive/Ghana Wav 3 Files/01gii_edcareer.dta')
df_power_1 = pd.read_stata('/content/drive/MyDrive/Ghana Wav 3 Files/07b_power-1.dta')
df_power_2 = pd.read_stata('/content/drive/MyDrive/Ghana Wav 3 Files/08b-power-2.dta')
df_asset_q = pd.read_stata('/content/drive/MyDrive/Ghana Wav 3 Files/05aii_assetquestions_osp.dta')
df_employment= pd.read_stata('/content/drive/MyDrive/Ghana Wav 3 Files/01fi_employmentmain.dta')

In [76]:
print(df_eng.shape)
print(df_gen_ed.shape)
print(df_ed_career.shape)
print(df_unemployed.shape)
print(df_math.shape)
print(df_employment.shape)
print(df_asset_q.shape)
print(df_power_1)
print(df_power_2)

#Dylan--I went ahead and split up the cells to make it easier to digest
#Dylan--I also cant see the dataframes since they were mounted from Corinne's drive, hopefully it does the trick

Streaming output truncated to the last 5000 lines.
14006                      NaN
14007                      NaN
14008                      NaN
14009                      NaN
14010                      NaN
14011                    Never
14012                      NaN
14013                      NaN
14014                      NaN
14015                      NaN
14016                    Never
14017                      NaN
14018                      NaN
14019                      NaN
14020                      NaN
14021                      NaN
14022                      NaN
14023                      NaN
14024                      NaN
14025                      NaN
14026                    Never
14027                      NaN
14028                      NaN
14029                      NaN
14030                      NaN
14031                      NaN
14032                    Never
14033                      NaN
14034                      NaN
14035                      NaN
14036                    Never
14037                      NaN
14038                      NaN
14039                      NaN
14040                    Never
14041                      NaN
14042                    Never
14043                      NaN
14044                      NaN
14045                      NaN
14046                      NaN
14047                    Never
14048                      NaN
14049                      NaN
14050                      NaN
14051                      NaN
14052                      NaN
14053                      NaN
14054                    Never
14055                      NaN
14056                      NaN
14057                      NaN
14058                      NaN
14059                      NaN
14060                      NaN
14061                    Never
14062                      NaN
14063                      NaN
14064                      NaN
14065                      NaN
14066                      NaN
14067                      NaN
14068                      NaN
14069                    Never
14070                      NaN
14071                      NaN
14072                      NaN
14073                      NaN
14074                    Never
14075                      NaN
14076                      NaN
14077                      NaN
14078                      NaN
14079                    Never
14080                      NaN
14081                    Never
14082                      NaN
14083                    Never
14084                      NaN
14085                      NaN
14086                    Never
14087                      NaN
14088                      NaN
14089                      NaN
14090                      NaN
14091                    Never
14092                      NaN
14093                      NaN
14094                      NaN
14095                      NaN
14096                      NaN
14097                      NaN
14098                      NaN
14099                      NaN
14100                      NaN
14101                      NaN
14102                    Never
14103                      NaN
14104                      NaN
14105                      NaN
14106                      NaN
14107                      NaN
14108                      NaN
14109                    Never
14110                      NaN
14111                    Never
14112                      NaN
14113                      NaN
14114                      NaN
14115                      NaN
14116                      NaN
14117                      NaN
14118                      NaN
14119                    Never
14120                      NaN
14121                      NaN
14122                      NaN
14123                      NaN
14124                      NaN
14125                      NaN
14126                      NaN
14127                      NaN
14128                    Never
14129                      NaN
14130                      NaN
14131                      NaN
14132                      NaN
14133                      NaN
14134                    Never
14135                      NaN
14136                      NaN
14137                      NaN
14138                      NaN
14139                    Never
14140                      NaN
14141                      NaN
14142                      NaN
14143                      NaN
14144                      NaN
14145                      NaN
14146                      NaN
14147                      NaN
14148                    Never
14149                      NaN
14150                      NaN
14151                    Never
14152                      NaN
14153                      NaN
14154                      NaN
14155                      NaN
14156                    Never
14157                      NaN
14158                      NaN
14159                      NaN
14160                    Never
14161                      NaN
14162                      NaN
14163                      NaN
14164                      NaN
14165                    Never
14166                      NaN
14167                      NaN
14168                      NaN
14169                      NaN
14170                      NaN
14171                    Never
14172                    Never
14173                      NaN
14174                      NaN
14175                      NaN
14176                      NaN
14177                      NaN
14178                    Never
14179                      NaN
14180                      NaN
14181                      NaN
14182                      NaN
14183                      NaN
14184                      NaN
14185                      NaN
14186                      NaN
14187                      NaN
14188                      NaN
14189                    Never
14190                      NaN
14191                      NaN
14192                      NaN
14193                      NaN
14194                      NaN
14195                      NaN
14196                      NaN
14197                      NaN
14198                      NaN
14199                    Never
14200                      NaN
14201                      NaN
14202                      NaN
14203                      NaN
14204                      NaN
14205                    Never
14206                      NaN
14207                      NaN
14208                      NaN
14209                      NaN
14210                      NaN
14211                      NaN
14212                    Never
14213                      NaN
14214                      NaN
14215                      NaN
14216                      NaN
14217                      NaN
14218                      NaN
14219                      NaN
14220                      NaN
14221                      NaN
14222                      NaN
14223                      NaN
14224                      NaN
14225                    Never
14226                      NaN
14227                      NaN
14228                      NaN
14229                      NaN
14230                      NaN
14231                      NaN
14232                      NaN
14233                      NaN
14234                      NaN
14235                      NaN
14236                      NaN
14237                      NaN
14238                    Never
14239                      NaN
14240                      NaN
14241                      NaN
14242                      NaN
14243                      NaN
14244                      NaN
14245                      NaN
14246                    Never
14247                      NaN
14248                      NaN
14249                      NaN
14250                      NaN
14251                      NaN
14252                      NaN
14253                      NaN
14254                      NaN
14255                    Never
14256                      NaN
14257                      NaN
14258                      NaN
14259                      NaN
14260                      NaN
14261                      NaN
14262                      NaN
14263                      NaN
14264                      NaN
14265                      NaN
14266                      NaN
14267                      NaN
14268                    Never
14269                      NaN
14270                      NaN
14271                      NaN
14272                      NaN
14273                      NaN
14274                      NaN
14275                      NaN
14276                      NaN
14277                      NaN
14278                      NaN
14279                      NaN
14280                      NaN
14281                    Never
14282                      NaN
14283                      NaN
14284                      NaN
14285                      NaN
14286                      NaN
14287                      NaN
14288                      NaN
14289                    Never
14290                      NaN
14291                      NaN
14292                      NaN
14293                      NaN
14294                      NaN
14295                    Never
14296                      NaN
14297                      NaN
14298                      NaN
14299                    Never
14300                      NaN
14301                      NaN
14302                      NaN
14303                      NaN
14304                      NaN
14305                      NaN
14306                      NaN
14307                    Never
14308                      NaN
14309                      NaN
14310                      NaN
14311                      NaN
14312                      NaN
14313                      NaN
14314                      NaN
14315                      NaN
14316                      NaN
14317                      NaN
14318                      NaN
14319                      NaN
14320                      NaN
14321                      NaN
14322                      NaN
14323                      NaN
14324                    Never
14325                      NaN
14326                      NaN
14327                      NaN
14328                      NaN
14329                      NaN
14330                    Never
14331                      NaN
14332                      NaN
14333                      NaN
14334                      NaN
14335                      NaN
14336                      NaN
14337                      NaN
14338                    Never
14339                      NaN
14340                      NaN
14341                      NaN
14342                      NaN
14343                      NaN
14344                      NaN
14345                      NaN
14346                    Never
14347                      NaN
14348                      NaN
14349                      NaN
14350                      NaN
14351                      NaN
14352                      NaN
14353                      NaN
14354                      NaN
14355                      NaN
14356                      NaN
14357                      NaN
14358                    Never
14359                      NaN
14360                      NaN
14361                      NaN
14362                      NaN
14363                    Never
14364                      NaN
14365                      NaN
14366                      NaN
14367                      NaN
14368                      NaN
14369                      NaN
14370                      NaN
14371                    Never
14372                      NaN
14373                      NaN
14374                      NaN
14375                      NaN
14376                    Never
14377                      NaN
14378                      NaN
14379                      NaN
14380                      NaN
14381                      NaN
14382                    Never
14383                      NaN
14384                      NaN
14385                      NaN
14386                      NaN
14387                    Never
14388                      NaN
14389                      NaN
14390                    Never
14391                      NaN
14392                      NaN
14393                      NaN
14394                      NaN
14395                      NaN
14396                      NaN
14397                      NaN
14398                      NaN
14399                      NaN
14400                      NaN
14401                      NaN
14402                      NaN
14403                      NaN
14404                      NaN
14405                      NaN
14406                      NaN
14407                      NaN
14408                      NaN
14409                      NaN
14410                    Never
14411                      NaN
14412                      NaN
14413                      NaN
14414                      NaN
14415                      NaN
14416                      NaN
14417                      NaN
14418                      NaN
14419                      NaN
14420                      NaN
14421                    Never
14422                      NaN
14423                      NaN
14424                      NaN
14425                      NaN
14426                      NaN
14427                    Never
14428                      NaN
14429                      NaN
14430                      NaN
14431                      NaN
14432                      NaN
14433                    Never
14434                      NaN
14435                      NaN
14436                      NaN
14437                    Never
14438                      NaN
14439                      NaN
14440                    Never
14441                      NaN
14442                    Never
14443                      NaN
14444                      NaN
14445                      NaN
14446                      NaN
14447                      NaN
14448                    Never
14449                      NaN
14450                      NaN
14451                      NaN
14452                      NaN
14453                      NaN
14454                      NaN
14455                      NaN
14456                      NaN
14457                      NaN
14458                      NaN
14459                    Never
14460                      NaN
14461                    Never
14462                      NaN
14463                      NaN
14464                    Never
14465                      NaN
14466                      NaN
14467                    Never
14468                      NaN
14469                      NaN
14470                      NaN
14471                      NaN
14472                      NaN
14473                      NaN
14474                    Never
14475                      NaN
14476                      NaN
14477                      NaN
14478                      NaN
14479                    Never
14480                      NaN
14481                      NaN
14482                      NaN
14483                      NaN
14484                    Never
14485                      NaN
14486                    Never
14487                      NaN
14488                      NaN
14489                      NaN
14490                      NaN
14491                      NaN
14492                      NaN
14493                      NaN
14494                      NaN
14495                    Never
14496                      NaN
14497                      NaN
14498                      NaN
14499                      NaN
14500                      NaN
14501                      NaN
14502                      NaN
14503                      NaN
14504                      NaN
14505                      NaN
14506                      NaN
14507                      NaN
14508                      NaN
14509                     Once
14510                      NaN
14511                      NaN
14512                      NaN
14513                      NaN
14514                    Never
14515                      NaN
14516                      NaN
14517                      NaN
14518                      NaN
14519                    Never
14520                      NaN
14521                      NaN
14522                      NaN
14523                    Never
14524                      NaN
14525                    Never
14526                      NaN
14527                      NaN
14528                      NaN
14529                      NaN
14530                    Never
14531                      NaN
14532                      NaN
14533                      NaN
14534                    Never
14535                      NaN
14536                      NaN
14537                      NaN
14538                    Never
14539                      NaN
14540                      NaN
14541                      NaN
14542                      NaN
14543                      NaN
14544                      NaN
14545                      NaN
14546                    Never
14547                    Never
14548                      NaN
14549                      NaN
14550                      NaN
14551                      NaN
14552                      NaN
14553                      NaN
14554                      NaN
14555                      NaN
14556                    Never
14557                      NaN
14558                    Never
14559                    Never
14560                      NaN
14561                      NaN
14562                      NaN
14563                    Never
14564                      NaN
14565                      NaN
14566                      NaN
14567                      NaN
14568                      NaN
14569                      NaN
14570                      NaN
14571                      NaN
14572                      NaN
14573                      NaN
14574                    Never
14575                      NaN
14576                      NaN
14577                      NaN
14578                      NaN
14579                      NaN
14580                    Never
14581                      NaN
14582                      NaN
14583                      NaN
14584                      NaN
14585                      NaN
14586                    Never
14587                      NaN
14588                      NaN
14589                      NaN
14590                      NaN
14591                      NaN
14592                      NaN
14593                      NaN
14594                      NaN
14595                      NaN
14596                      NaN
14597                      NaN
14598                      NaN
14599                      NaN
14600                      NaN
14601                      NaN
14602                      NaN
14603                      NaN
14604                    Never
14605                      NaN
14606                      NaN
14607                      NaN
14608                      NaN
14609                    Never
14610                      NaN
14611                      NaN
14612                      NaN
14613                      NaN
14614                      NaN
14615                      NaN
14616                      NaN
14617                      NaN
14618                      NaN
14619                      NaN
14620                      NaN
14621                      NaN
14622                      NaN
14623                      NaN
14624                    Never
14625                    Never
14626                      NaN
14627                      NaN
14628                      NaN
14629                      NaN
14630                      NaN
14631                      NaN
14632                    Never
14633                      NaN
14634                      NaN
14635                    Never
14636                      NaN
14637                      NaN
14638                      NaN
14639                      NaN
14640                    Never
14641                      NaN
14642                      NaN
14643                      NaN
14644                      NaN
14645                      NaN
14646                      NaN
14647                      NaN
14648                    Never

In [77]:
df_eng.tail(10)
df_eng.head(10)

,FPrimary,index,hhmid,age,new_mem,available,ever_attended,english_starttime,english_09,english_09_yn,english_10,english_10_yn,english_11,english_11_yn,english_12,english_12_yn,english_13,english_13_yn,english_14,english_14_yn,english_15,english_15_yn,english_endtime,english_score
0,1008308001,1,1,20,0.0,Yes,No,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN
1,1009320001,1,2,17,0.0,Yes,Yes,1:36:00 PM,B) A small boy,Yes,A) In a village,Yes,C) Helps his brothers/sisters,No,C) Five,Yes,C) Learning to read,Yes,C) John's brother,No,A) Go to school,No,1:39:00 PM,4.0
2,1009320001,2,1,80,0.0,Yes,No,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN
3,1009320001,3,3,15,1.0,Yes,Yes,12:58:00 PM,B) A small boy,Yes,A) In a village,Yes,D) Goes to school,Yes,C) Five,Yes,C) Learning to read,Yes,B) John's father,Yes,D) Become a teacher,Yes,12:59:00 PM,7.0
4,101001002,1,1,35,0.0,Yes,Yes,1:49:00 AM,B) A small boy,Yes,A) In a village,Yes,D) Goes to school,Yes,C) Five,Yes,C) Learning to read,Yes,B) John's father,Yes,D) Become a teacher,Yes,1:52:00 AM,7.0
5,101001002,2,2,30,0.0,Yes,Yes,11:36:00 PM,NaN,No,NaN,No,NaN,No,NaN,No,NaN,No,NaN,No,NaN,No,11:39:00 PM,0.0
6,101001002,3,5,9,0.0,Yes,Yes,5:54:00 PM,B) A small boy,Yes,A) In a village,Yes,C) Helps his brothers/sisters,No,B) Three,No,C) Learning to read,Yes,B) John's father,Yes,A) Go to school,No,5:57:00 PM,4.0
7,101001002,4,6,6,0.0,Yes,Yes,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN
8,101001003,1,1,33,0.0,Yes,Yes,4:33:00 PM,B) A small boy,Yes,A) In a village,Yes,D) Goes to school,Yes,C) Five,Yes,C) Learning to read,Yes,B) John's father,Yes,D) Become a teacher,Yes,4:38:00 PM,7.0
9,101001003,2,2,30,0.0,Yes,Yes,7:36:00 AM,B) A small boy,Yes,A) In a village,Yes,D) Goes to school,Yes,C) Five,Yes,C) Learning to read,Yes,B) John's father,Yes,D) Become a teacher,Yes,7:39:00 AM,7.0

In [78]:
df_math.tail(10)
df_math.head(10)

,FPrimary,index,hhmid,age,new_mem,available,ever_attended,math_starttime,math_01,math_01_yn,math_02,math_02_yn,math_03,math_03_yn,math_04,math_04_yn,math_05,math_05_yn,math_06,math_06_yn,math_07,math_07_yn,math_08,math_08_yn,math_endtime,math_score
0,1008308001,1,1,20,0.0,Yes,No,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN
1,1009320001,1,2,17,0.0,Yes,Yes,1:25:00 PM,D) 3,Yes,C) 3,Yes,B) 6,Yes,C) 2,Yes,D) 22,Yes,D) 13,No,B) 51,Yes,C) 6,Yes,1:27:00 PM,7.0
2,1009320001,2,1,80,0.0,Yes,No,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN
3,1009320001,3,3,15,1.0,Yes,Yes,12:48:00 PM,D) 3,Yes,C) 3,Yes,B) 6,Yes,C) 2,Yes,D) 22,Yes,B) 14,Yes,B) 51,Yes,C) 6,Yes,12:49:00 PM,8.0
4,101001002,1,1,35,0.0,Yes,Yes,12:39:00 AM,D) 3,Yes,C) 3,Yes,B) 6,Yes,C) 2,Yes,D) 22,Yes,D) 13,No,B) 51,Yes,C) 6,Yes,12:42:00 AM,7.0
5,101001002,2,2,30,0.0,Yes,Yes,11:33:00 PM,B) 8,No,D) 1,No,D) 8,No,D) 50,No,D) 22,Yes,A) 10,No,D) 50,No,E) None of the above,No,11:36:00 PM,1.0
6,101001002,3,5,9,0.0,Yes,Yes,5:43:00 PM,D) 3,Yes,C) 3,Yes,A) 5,No,B) 15,No,B) 21,No,B) 14,Yes,A) 5.7,No,B) 9,No,5:45:00 PM,3.0
7,101001002,4,6,6,0.0,Yes,Yes,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN
8,101001003,1,1,33,0.0,Yes,Yes,4:22:00 PM,D) 3,Yes,C) 3,Yes,B) 6,Yes,C) 2,Yes,D) 22,Yes,B) 14,Yes,B) 51,Yes,C) 6,Yes,4:25:00 PM,8.0
9,101001003,2,2,30,0.0,Yes,Yes,7:22:00 AM,D) 3,Yes,C) 3,Yes,B) 6,Yes,C) 2,Yes,D) 22,Yes,B) 14,Yes,B) 51,Yes,C) 6,Yes,7:24:00 AM,8.0

In [79]:
df_employment.tail(20)
df_employment.head(20)

,FPrimary,index,hhmid,age,interviewedid,paidemployed,maintasks,taskdescription,taskcode,maintrade,tradecode,joblengthyears,joblengthmonths,jobweeksperyear,jobdaysperweek,jobhoursperday,last7daysperweek,last7hoursperday,paid,paidamount,paidperiod,paidperiodother,paidother,paidothervalue,paidotherperiod,paidotherperiodother,contract,unionyesno,jobholidays,jobsickleave,jobsickleave_0,jobsickleave_1,jobsickleave_2,jobsickleave_3,jobsickleave_4,jobsickleave_888,jobsickleave_999,jobpension,jobtaxes,jobmedcare,jobsocialsec,jobwhere,jobpeople,jobtraining,trainingmonths,trainingweeks,trainingdays,trainingtype,trainingtype_1,trainingtype_2,trainingtype_3,trainingtype_4,trainingtype_5,trainingtype_6,trainingtype_7,trainingtype_8,trainingtype_9,trainingtype_666,trainingtype_888,trainingtype_999,trainingtypeother,trainingpaid,trainingpaidother,traininglose,traininglosewhat
0,101001009,1,1,33,${s1b2_temp_name_1},Yes,1.0,Teaching JHS,234,Teacher,8510,1.0,2.0,40.0,5.0,8.0,3.0,24.0,Yes,750.0,Monthly,,No,NaN,NaN,,Yes,Yes,Yes,1 4,0,1,0,0,1,0,0,Yes,Yes,No,Yes,School,13.0,No,NaN,NaN,NaN,,0,0,0,0,0,0,0,0,0,0,0,0,,NaN,,NaN,NaN
1,101002041,1,1,45,${s1b2_temp_name_1},Yes,1.0,Checking of passport at the border,422,Transport Agency,7911,25.0,6.0,50.0,6.0,9.0,6.0,9.0,Yes,600.0,Monthly,,No,NaN,NaN,,Yes,Yes,Yes,-999,0,0,0,0,0,0,1,Yes,No,Yes,Yes,Street at a fixed location,11.0,No,NaN,NaN,NaN,,0,0,0,0,0,0,0,0,0,0,0,0,,NaN,,NaN,NaN
2,101002052,1,1,58,${s1b2_temp_name_1},Yes,1.0,Luggage Potter,962,Carries luggage at the market and station for ...,9609,3.0,11.0,21.0,3.0,5.0,3.0,4.0,Yes,30.0,Daily,,No,NaN,NaN,,No,No,No,0,1,0,0,0,0,0,0,No,No,No,No,Street not at a fixed location,600.0,No,NaN,NaN,NaN,,0,0,0,0,0,0,0,0,0,0,0,0,,NaN,,NaN,NaN
3,101003012,1,1,45,${s1b2_temp_name_1},Yes,1.0,Fisherman,921,Fishing,311,0.0,5.0,3.0,5.0,3.0,0.0,0.0,Yes,10.0,Daily,,Yes,5.0,Daily,,No,No,No,0,1,0,0,0,0,0,0,No,No,No,No,River/ocean,25.0,No,NaN,NaN,NaN,,0,0,0,0,0,0,0,0,0,0,0,0,,NaN,,NaN,NaN
4,101003012,3,3,17,${s1b2_temp_name_3},Yes,1.0,Fisherman,921,Fishing,311,0.0,1.0,4.0,2.0,11.0,2.0,5.0,Yes,20.0,Daily,,Yes,2.0,Daily,,No,No,No,0,1,0,0,0,0,0,0,No,No,No,No,River/ocean,21.0,No,NaN,NaN,NaN,,0,0,0,0,0,0,0,0,0,0,0,0,,NaN,,NaN,NaN
5,101003012,8,8,19,${s1b2_temp_name_8},Yes,1.0,Fisherman,921,Fishing,311,2.0,3.0,43.0,5.0,5.0,1.0,5.0,Yes,15.0,Daily,,No,NaN,NaN,,No,No,No,0,1,0,0,0,0,0,0,No,Yes,No,No,River/ocean,20.0,No,NaN,NaN,NaN,,0,0,0,0,0,0,0,0,0,0,0,0,,NaN,,NaN,NaN
6,101003026,2,2,32,${s1b2_temp_name_2},Yes,1.0,Construction Labourer,711,Building construction,4100,1.0,6.0,48.0,2.0,6.0,2.0,6.0,Yes,60.0,Daily,,No,NaN,NaN,,No,No,No,0,1,0,0,0,0,0,0,No,Yes,No,Yes,Other (please specify),5.0,No,NaN,NaN,NaN,,0,0,0,0,0,0,0,0,0,0,0,0,,NaN,,NaN,NaN
7,101003032,3,3,26,${s1b2_temp_name_3},Yes,1.0,Football,342,Games,9311,4.0,6.0,52.0,5.0,2.0,5.0,2.0,Yes,700.0,Monthly,,No,NaN,NaN,,Yes,No,Yes,1 3,0,1,0,1,0,0,0,No,Yes,Yes,No,Other (please specify),23.0,Yes,6.0,0.0,0.0,9,0,0,0,0,0,0,0,0,1,0,0,0,,Employer entirely,,No,NaN
8,101003037,1,1,58,${s1b2_temp_name_1},Yes,1.0,Taps Palm wine,932,Manufacturing and wholesale,1101,1.0,0.0,52.0,6.0,11.0,6.0,11.0,Yes,50.0,Not regular,,No,NaN,NaN,,No,No,No,0,1,0,0,0,0,0,0,No,No,No,No,Other (please specify),2.0,No,NaN,NaN,NaN,,0,0,0,0,0,0,0,0,0,0,0,0,,NaN,,NaN,NaN
9,101003050,6,6,19,${s1b2_temp_name_6},Yes,1.0,Apprentice at Seamstress shop,731,Manufacturing,1410,0.0,11.0,50.0,5.0,8.0,4.0,8.0,No,NaN,NaN,,No,NaN,NaN,,No,No,No,0,1,0,0,0,0,0,0,No,No,No,No,Store/shop/table shop,5.0,No,NaN,NaN,NaN,,0,0,0,0,0,0,0,0,0,0,0,0,,NaN,,NaN,NaN
10,101004001,1,1,64,${s1b2_temp_name_1},Yes,1.0,Teaching,233,Education,8510,7.0,6.0,52.0,5.0,6.0,5.0,6.0,Yes,1500.0,Monthly,,No,NaN,NaN,,Yes,Yes,Yes,1 3 4,0,1,0,1,1,0,0,Yes,Yes,Yes,Yes,School,7.0,Yes,0.0,1.0,3.0,5,0,0,0,0,1,0,0,0,0,0,0,0,,Employer entirely,,No,NaN
11,101004006,1,2,56,${s1b2_temp_name_2},Yes,1.0,Teaching,234,Education,8510,25.0,2.0,36.0,5.0,6.0,5.0,6.0,Yes,600.0,Monthly,,No,NaN,NaN,,Yes,Yes,Yes,1 2,0,1,1,0,0,0,0,Yes,Yes,No,Yes,School,15.0,No,NaN,NaN,NaN,,0,0,0,0,0,0,0,0,0,0,0,0,,NaN,,NaN,NaN
12,101004010,3,5,24,${s1b2_temp_name_1},Yes,1.0,Nursing officer,222,Health services,8620,3.0,0.0,52.0,5.0,8.0,0.0,0.0,Yes,300.0,Monthly,,No,NaN,NaN,,Yes,No,Yes,1 2 3 4,0,1,1,1,1,0,0,No,Yes,Yes,No,Hospital/clinic,7.0,No,NaN,NaN,NaN,,0,0,0,0,0,0,0,0,0,0,0,0,,NaN,,NaN,NaN
13,101004014,1,1,53,${s1b2_temp_name_2},Yes,1.0,Security person at Electricity Company of Ghan...,541,Security person at Electricity Company of Ghan...,8081,1.0,2.0,52.0,7.0,12.0,7.0,12.0,Yes,450.0,Monthly,,No,NaN,NaN,,Yes,Yes,Yes,1,0,1,0,0,0,0,0,Yes,Yes,Yes,No,Factory,60.0,No,NaN,NaN,NaN,,0,0,0,0,0,0,0,0,0,0,0,0,,NaN,,NaN,NaN
14,101004024,1,1,31,${s1b2_temp_name_1},Yes,1.0,Ensuring the cleanliness of the beach,325,Sanitation,8130,2.0,0.0,48.0,5.0,3.0,5.0,3.0,Yes,250.0,Monthly,,No,NaN,NaN,,Yes,No,Yes,1,0,1,0,0,0,0,0,No,Yes,No,No,River/ocean,4.0,No,NaN,NaN,NaN,,0,0,0,0,0,0,0,0,0,0,0,0,,NaN,,NaN,NaN
15,101004027,1,1,48,${s1b2_temp_name_1},Yes,1.0,Laborer at Adamus mines,931,Mining and construction,890,6.0,8.0,50.0,5.0,9.0,5.0,9.0,Yes,900.0,Monthly,,No,NaN,NaN,,Yes,Yes,Yes,1,0,1,0,0,0,0,0,Yes,Yes,Yes,No,Factory,53.0,Yes,0.0,2.0,0.0,-666,0,0,0,0,0,0,0,0,0,1,0,0,Safety,Employer entirely,,No,NaN
16,101005003,2,2,31,${s1b2_temp_name_2},Yes,1.0,Works on a non-household member farm,611,Growing of cocoa,127,2.0,3.0,1.0,7.0,6.0,6.0,6.0,Yes,10.0,Daily,,Yes,50.0,Not regular,,No,No,No,0,1,0,0,0,0,0,0,No,No,No,No,Other land/farm,6.0,No,NaN,NaN,NaN,,0,0,0,0,0,0,0,0,0,0,0,0,,NaN,,NaN,NaN
17,101005033,3,3,24,${s1b2_temp_name_3},Yes,1.0,Housekeeping (Cleaning),515,Hospitality /Hotel,5510,0.0,4.0,16.0,7.0,10.0,7.0,7.0,Yes,350.0,Monthly,,No,NaN,NaN,,Yes,No,Yes,1,0,1,0,0,0,0,0,Yes,Yes,Yes,Yes,Hotel/restaurant,16.0,Yes,1.0,0.0,0.0,-666,0,0,0,0,0,0,0,0,0,1,0,0,Housekeeping training,Employer entirely,,No,NaN
18,101005036,2,4,26,${s1b2_temp_name_2},Yes,1.0,Served and distributed food,513,Hospitality Services,5610,0.0,3.0,12.0,5.0,8.0,5.0,8.0,Yes,84.0,Monthly,,Yes,12.0,Monthly,,Yes,No,Yes,1 3 4,0,1,0,1,1,0,0,Yes,Yes,Yes,Yes,Hotel/restaurant,NaN,Yes,0.0,0.0,2.0,4,0,0,0,1,0,0,0,0,0,0,0,0,,Employer entirely,,No,NaN
19,101005041,1,1,59,${s1b2_temp_name_1},Yes,1.0,Cooks at a schools canteen,941,Secondary Education,8522,0.0,7.0,2.0,6.0,9.0,5.0,9.0,Yes,0.0,Daily,,Yes,300.0,Quarterly,,No,Yes,No,0,1,0,0,0,0,0,0,No,Yes,No,No,School,12.0,No,NaN,NaN,NaN,,0,0,0,0,0,0,0,0,0,0,0,0,,NaN,,NaN,NaN

In [80]:
df_gen_ed.tail(15)
df_gen_ed.head(15)

,FPrimary,index,hhmid,age,relationship,new_mem,interviewedid,attended,highestgrade,highestqual,highestqualother,attendedlast12,attendingstill,currentgrade,schooltype,schoolcode,travelschoolhours,travelschoolminutes,classhours,classminutes,missedhours,missedminutes,homeworkhours,homeworkminutes,expendbreakdown,last12schoolfees,last12pta,last12uniforms,last12books,last12transport,last12foodboard,last12extraclass,last12inkind,last12totalexpend,last12estexpend,whopaid,last12scholarship,last12scholarshipamt,booksaccess,bookshow,bookshow_1,bookshow_2,bookshow_3,bookshow_4,bookshow_5,bookshow_6,bookshow_666,bookshow_888,bookshow_999,bookshowother,feedingprogram,mealsatschool,meal_index_1,meal_name_1,mealsatschoolperweek_1,meal_index_2,meal_name_2,mealsatschoolperweek_2,meal_index_3,meal_name_3,mealsatschoolperweek_3,meal_index_4,meal_name_4,mealsatschoolperweek_4,schooltransport,schooltransportother,oneteacher,teacherabsent,englangteacherabsent,mathteacherabsent,repeatgradeever,repeatgradetimes,skipgradeever,skipgradetimes,apply_secondary,apply_program,apply_program_1,apply_program_2,apply_program_3,apply_program_4,apply_program_5,apply_program_6,apply_program_666,apply_program_888,apply_program_999,apply_programother,admitted_secondary,admitted_program,admitted_programother,ideal_program,ideal_programother
0,1008308001,1,1,20,1,0.0,${s1b2_temp_name_1},Yes,JSS1,None,,No,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0,0,0,0,0,0,0,0,0,,NaN,,NaN,,NaN,NaN,,NaN,NaN,,NaN,NaN,,NaN,NaN,,NaN,NaN,NaN,NaN,No,NaN,No,NaN,NaN,,0,0,0,0,0,0,0,0,0,,NaN,NaN,,NaN,
1,1009320001,1,2,17,4,0.0,${s1b2_temp_name_1},Yes,JSS2,None,,Yes,Yes,JSS3,Public and non-religious,-666,0.0,20.0,38.0,45.0,0.0,0.0,5.0,0.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201.0,Mother,No,NaN,Has some but not all books needed,3,0,0,1,0,0,0,0,0,0,,No,,NaN,,NaN,NaN,,NaN,NaN,,NaN,NaN,,NaN,Walk,,No,NaN,0.0,0.0,No,NaN,No,NaN,No,,0,0,0,0,0,0,0,0,0,,NaN,NaN,,Other (please specify),Agric Science
2,1009320001,2,1,80,1,0.0,${s1b2_temp_name_2},No,NaN,NaN,,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0,0,0,0,0,0,0,0,0,,NaN,,NaN,,NaN,NaN,,NaN,NaN,,NaN,NaN,,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0,0,0,0,0,0,0,0,0,,NaN,NaN,,NaN,
3,1009320001,3,3,15,4,1.0,${s1b2_temp_name_3},Yes,JSS2,None,,Yes,Yes,JSS3,Public and non-religious,-666,0.0,20.0,38.0,45.0,0.0,0.0,5.0,0.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201.0,Mother,No,NaN,Has some but not all books needed,3,0,0,1,0,0,0,0,0,0,,No,,NaN,,NaN,NaN,,NaN,NaN,,NaN,NaN,,NaN,Walk,,No,NaN,0.0,0.0,No,NaN,No,NaN,No,,0,0,0,0,0,0,0,0,0,,NaN,NaN,,Visual arts,
4,101001002,1,1,35,1,0.0,${s1b2_temp_name_1},Yes,SSS3,SSCE,,No,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0,0,0,0,0,0,0,0,0,,NaN,,NaN,,NaN,NaN,,NaN,NaN,,NaN,NaN,,NaN,NaN,,NaN,NaN,NaN,NaN,No,NaN,Yes,1.0,NaN,,0,0,0,0,0,0,0,0,0,,NaN,NaN,,NaN,
5,101001002,2,2,30,2,0.0,${s1b2_temp_name_1},Yes,Pre-school,None,,No,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0,0,0,0,0,0,0,0,0,,NaN,,NaN,,NaN,NaN,,NaN,NaN,,NaN,NaN,,NaN,NaN,,NaN,NaN,NaN,NaN,No,NaN,No,NaN,NaN,,0,0,0,0,0,0,0,0,0,,NaN,NaN,,NaN,
6,101001002,3,5,9,3,0.0,${s1b2_temp_name_1},Yes,P1,None,,Yes,Yes,P2,Public and religious,101603,0.0,20.0,30.0,0.0,0.0,0.0,2.0,30.0,Yes,30.0,15.0,0.0,36.0,0.0,0.0,0.0,30.0,111.0,NaN,Father,No,NaN,"Yes, has all books needed",2,0,1,0,0,0,0,0,0,0,,Yes,3,1.0,Lunch,1.0,NaN,,NaN,NaN,,NaN,NaN,,NaN,Walk,,Yes,0.0,NaN,NaN,No,NaN,No,NaN,Yes,1,1,0,0,0,0,0,0,0,0,,No,NaN,,Visual arts,
7,101001002,4,6,6,3,0.0,${s1b2_temp_name_1},Yes,None,None,,Yes,Yes,Pre-school,Public and religious,101604,0.0,20.0,30.0,0.0,0.0,0.0,0.0,0.0,Yes,30.0,15.0,30.0,30.0,0.0,0.0,0.0,30.0,135.0,NaN,Father,No,NaN,"Yes, has all books needed",2,0,1,0,0,0,0,0,0,0,,Yes,3,1.0,Lunch,1.0,NaN,,NaN,NaN,,NaN,NaN,,NaN,Walk,,Yes,0.0,NaN,NaN,No,NaN,No,NaN,NaN,,0,0,0,0,0,0,0,0,0,,NaN,NaN,,NaN,
8,101001002,5,7,2,3,1.0,${s1b2_temp_name_1},NaN,NaN,NaN,,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0,0,0,0,0,0,0,0,0,,NaN,,NaN,,NaN,NaN,,NaN,NaN,,NaN,NaN,,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0,0,0,0,0,0,0,0,0,,NaN,NaN,,NaN,
9,101001003,1,1,33,1,0.0,${s1b2_temp_name_1},Yes,SSS3,SSCE,,No,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0,0,0,0,0,0,0,0,0,,NaN,,NaN,,NaN,NaN,,NaN,NaN,,NaN,NaN,,NaN,NaN,,NaN,NaN,NaN,NaN,No,NaN,No,NaN,NaN,,0,0,0,0,0,0,0,0,0,,NaN,NaN,,NaN,
10,101001003,2,2,30,2,0.0,${s1b2_temp_name_1},Yes,JSS3,BECE,,No,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0,0,0,0,0,0,0,0,0,,NaN,,NaN,,NaN,NaN,,NaN,NaN,,NaN,NaN,,NaN,NaN,,NaN,NaN,NaN,NaN,Yes,1.0,No,NaN,NaN,,0,0,0,0,0,0,0,0,0,,NaN,NaN,,NaN,
11,101001003,3,3,5,3,0.0,${s1b2_temp_name_1},Yes,None,None,,Yes,Yes,Pre-school,Private and non-religious,-666,0.0,40.0,37.0,30.0,0.0,0.0,1.0,0.0,Yes,148.0,0.0,50.0,120.0,0.0,0.0,24.0,9.0,351.0,NaN,Father,No,NaN,"Yes, has all books needed",2,0,1,0,0,0,0,0,0,0,,No,,NaN,,NaN,NaN,,NaN,NaN,,NaN,NaN,,NaN,Walk,,Yes,0.0,NaN,NaN,No,NaN,No,NaN,NaN,,0,0,0,0,0,0,0,0,0,,NaN,NaN,,NaN,
12,101001003,4,4,7,3,0.0,${s1b2_temp_name_1},Yes,Pre-school,None,,Yes,Yes,P1,Private and non-religious,-666,0.0,40.0,37.0,30.0,0.0,0.0,0.0,30.0,Yes,187.0,0.0,50.0,60.0,0.0,0.0,24.0,15.0,336.0,NaN,Father,No,NaN,"Yes, has all books needed",2,0,1,0,0,0,0,0,0,0,,No,,NaN,,NaN,NaN,,NaN,NaN,,NaN,NaN,,NaN,Walk,,Yes,0.0,NaN,NaN,No,NaN,No,NaN,NaN,,0,0,0,0,0,0,0,0,0,,NaN,NaN,,NaN,
13,101001003,5,5,11,7,1.0,${s1b2_temp_name_1},Yes,P4,None,,Yes,Yes,P5,Public and religious,101603,0.0,10.0,32.0,30.0,0.0,0.0,0.0,50.0,Yes,108.0,0.0,0.0,108.0,0.0,0.0,0.0,45.0,261.0,NaN,Other relative,No,NaN,"Yes, has all books needed",2,0,1,0,0,0,0,0,0,0,,Yes,3,1.0,Lunch,1.0,NaN,,NaN,NaN,,NaN,NaN,,NaN,Walk,,Yes,0.0,NaN,NaN,No,NaN,No,NaN,No,,0,0,0,0,0,0,0,0,0,,NaN,NaN,,Business,
14,101001004,1,2,24,1,0.0,${s1b2_temp_name_1},Yes,JSS2,None,,No,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0,0,0,0,0,0,0,0,0,,NaN,,NaN,,NaN,NaN,,NaN,NaN,,NaN,NaN,,NaN,NaN,,NaN,NaN,NaN,NaN,No,NaN,Yes,1.0,NaN,,0,0,0,0,0,0,0,0,0,,NaN,NaN,,NaN,

In [81]:
print("Number of rows:", df_eng.shape[0])
print("Number of columns:", df_eng.shape[1])
print("Column names:")
print("\n".join(df_eng.columns))

Number of rows: 17103
Number of columns: 24
Column names:
FPrimary
index
hhmid
age
new_mem
available
ever_attended
english_starttime
english_09
english_09_yn
english_10
english_10_yn
english_11
english_11_yn
english_12
english_12_yn
english_13
english_13_yn
english_14
english_14_yn
english_15
english_15_yn
english_endtime
english_score

In [82]:
df_eng.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17103 entries, 0 to 17102
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   FPrimary           17103 non-null  object
 1   index              17103 non-null  int8
 2   hhmid              17103 non-null  int8
 3   age                17103 non-null  int16
 4   new_mem            17101 non-null  float64
 5   available          17003 non-null  category
 6   ever_attended      15283 non-null  category
 7   english_starttime  17103 non-null  object
 8   english_09         8913 non-null   category
 9   english_09_yn      10222 non-null  category
 10  english_10         8873 non-null   category
 11  english_10_yn      10222 non-null  category
 12  english_11         8890 non-null   category
 13  english_11_yn      10222 non-null  category
 14  english_12         8896 non-null   category
 15  english_12_yn      10222 non-null  category
 16  english_13         8868 non-null   category
 17  english_13_yn      10222 non-null  category
 18  english_14         8645 non-null   category
 19  english_14_yn      10222 non-null  category
 20  english_15         8855 non-null   category
 21  english_15_yn      10222 non-null  category
 22  english_endtime    17103 non-null  object
 23  english_score      10222 non-null  float64
dtypes: category(16), float64(2), int16(1), int8(2), object(3)
memory usage: 1004.8+ KB

In [83]:
def missing(df_eng):
  print('Percentage of missing values in the dataset:\n',
        round((df_eng.isnull().sum() * 100/ len(df_eng)),2). sort_values(ascending=False))

  missing(df_eng)

In [84]:
print("Number of rows:", df_math.shape[0])
print("Number of columns:", df_math.shape[1])
print("Column names:")
print("\n".join(df_math.columns))

Number of rows: 17103
Number of columns: 26
Column names:
FPrimary
index
hhmid
age
new_mem
available
ever_attended
math_starttime
math_01
math_01_yn
math_02
math_02_yn
math_03
math_03_yn
math_04
math_04_yn
math_05
math_05_yn
math_06
math_06_yn
math_07
math_07_yn
math_08
math_08_yn
math_endtime
math_score

In [85]:
df_math.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17103 entries, 0 to 17102
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   FPrimary        17103 non-null  object
 1   index           17103 non-null  int8
 2   hhmid           17103 non-null  int8
 3   age             17103 non-null  int16
 4   new_mem         17101 non-null  float64
 5   available       17003 non-null  category
 6   ever_attended   15283 non-null  category
 7   math_starttime  17103 non-null  object
 8   math_01         9958 non-null   category
 9   math_01_yn      10222 non-null  category
 10  math_02         9876 non-null   category
 11  math_02_yn      10222 non-null  category
 12  math_03         9817 non-null   category
 13  math_03_yn      10222 non-null  category
 14  math_04         9706 non-null   category
 15  math_04_yn      10222 non-null  category
 16  math_05         9644 non-null   category
 17  math_05_yn      10222 non-null  category
 18  math_06         9233 non-null   category
 19  math_06_yn      10222 non-null  category
 20  math_07         8949 non-null   category
 21  math_07_yn      10222 non-null  category
 22  math_08         8859 non-null   category
 23  math_08_yn      10222 non-null  category
 24  math_endtime    17103 non-null  object
 25  math_score      10222 non-null  float64
dtypes: category(18), float64(2), int16(1), int8(2), object(3)
memory usage: 1.0+ MB

In [86]:
df_math.isnull().sum()

FPrimary             0
index                0
hhmid                0
age                  0
new_mem              2
available          100
ever_attended     1820
math_starttime       0
math_01           7145
math_01_yn        6881
math_02           7227
math_02_yn        6881
math_03           7286
math_03_yn        6881
math_04           7397
math_04_yn        6881
math_05           7459
math_05_yn        6881
math_06           7870
math_06_yn        6881
math_07           8154
math_07_yn        6881
math_08           8244
math_08_yn        6881
math_endtime         0
math_score        6881
dtype: int64

In [87]:
print("Number of rows:", df_employment.shape[0])
print("Number of columns:", df_employment.shape[1])
print("Column names:")
print("\n".join(df_employment.columns))

Number of rows: 1481
Number of columns: 65
Column names:
FPrimary
index
hhmid
age
interviewedid
paidemployed
maintasks
taskdescription
taskcode
maintrade
tradecode
joblengthyears
joblengthmonths
jobweeksperyear
jobdaysperweek
jobhoursperday
last7daysperweek
last7hoursperday
paid
paidamount
paidperiod
paidperiodother
paidother
paidothervalue
paidotherperiod
paidotherperiodother
contract
unionyesno
jobholidays
jobsickleave
jobsickleave_0
jobsickleave_1
jobsickleave_2
jobsickleave_3
jobsickleave_4
jobsickleave_888
jobsickleave_999
jobpension
jobtaxes
jobmedcare
jobsocialsec
jobwhere
jobpeople
jobtraining
trainingmonths
trainingweeks
trainingdays
trainingtype
trainingtype_1
trainingtype_2
trainingtype_3
trainingtype_4
trainingtype_5
trainingtype_6
trainingtype_7
trainingtype_8
trainingtype_9
trainingtype_666
trainingtype_888
trainingtype_999
trainingtypeother
trainingpaid
trainingpaidother
traininglose
traininglosewhat

In [99]:
df_employment.info()
print(df_employment.dtypes)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1481 entries, 0 to 1480
Data columns (total 65 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   FPrimary              1481 non-null   object
 1   index                 1481 non-null   int8
 2   hhmid                 1481 non-null   int8
 3   age                   1481 non-null   int16
 4   interviewedid         1478 non-null   category
 5   paidemployed          1478 non-null   category
 6   maintasks             1478 non-null   float64
 7   taskdescription       1481 non-null   object
 8   taskcode              1481 non-null   object
 9   maintrade             1481 non-null   object
 10  tradecode             1481 non-null   object
 11  joblengthyears        1474 non-null   float64
 12  joblengthmonths       1419 non-null   float64
 13  jobweeksperyear       1453 non-null   float64
 14  jobdaysperweek        1476 non-null   float64
 15  jobhoursperday        1467 non-null   float64
 16  last7daysperweek      1476 non-null   float64
 17  last7hoursperday      1467 non-null   float64
 18  paid                  1478 non-null   category
 19  paidamount            1349 non-null   float32
 20  paidperiod            1411 non-null   category
 21  paidperiodother       1481 non-null   object
 22  paidother             1478 non-null   category
 23  paidothervalue        186 non-null    float64
 24  paidotherperiod       191 non-null    category
 25  paidotherperiodother  1481 non-null   object
 26  contract              1478 non-null   category
 27  unionyesno            1478 non-null   category
 28  jobholidays           1478 non-null   category
 29  jobsickleave          1481 non-null   object
 30  jobsickleave_0        1481 non-null   int8
 31  jobsickleave_1        1481 non-null   int8
 32  jobsickleave_2        1481 non-null   int8
 33  jobsickleave_3        1481 non-null   int8
 34  jobsickleave_4        1481 non-null   int8
 35  jobsickleave_888      1481 non-null   int8
 36  jobsickleave_999      1481 non-null   int8
 37  jobpension            1478 non-null   category
 38  jobtaxes              1478 non-null   category
 39  jobmedcare            1478 non-null   category
 40  jobsocialsec          1478 non-null   category
 41  jobwhere              1478 non-null   category
 42  jobpeople             1389 non-null   float64
 43  jobtraining           1478 non-null   category
 44  trainingmonths        192 non-null    float64
 45  trainingweeks         192 non-null    float64
 46  trainingdays          191 non-null    float64
 47  trainingtype          1481 non-null   object
 48  trainingtype_1        1481 non-null   int8
 49  trainingtype_2        1481 non-null   int8
 50  trainingtype_3        1481 non-null   int8
 51  trainingtype_4        1481 non-null   int8
 52  trainingtype_5        1481 non-null   int8
 53  trainingtype_6        1481 non-null   int8
 54  trainingtype_7        1481 non-null   int8
 55  trainingtype_8        1481 non-null   int8
 56  trainingtype_9        1481 non-null   int8
 57  trainingtype_666      1481 non-null   int8
 58  trainingtype_888      1481 non-null   int8
 59  trainingtype_999      1481 non-null   int8
 60  trainingtypeother     1481 non-null   object
 61  trainingpaid          193 non-null    category
 62  trainingpaidother     1481 non-null   object
 63  traininglose          193 non-null    category
 64  traininglosewhat      3 non-null      float64
dtypes: category(17), float32(1), float64(14), int16(1), int8(21), object(11)
memory usage: 356.1+ KB
FPrimary                  object
index                       int8
hhmid                       int8
age                        int16
interviewedid           category
paidemployed            category
maintasks                float64
taskdescription           object
taskcode                  object
maintrade                 object
tradecode                 object
joblengthyears           float64
joblengthmonths          float64
jobweeksperyear          float64
jobdaysperweek           float64
jobhoursperday           float64
last7daysperweek         float64
last7hoursperday         float64
paid                    category
paidamount               float32
paidperiod              category
paidperiodother           object
paidother               category
paidothervalue           float64
paidotherperiod         category
paidotherperiodother      object
contract                category
unionyesno              category
jobholidays             category
jobsickleave              object
jobsickleave_0              int8
jobsickleave_1              int8
jobsickleave_2              int8
jobsickleave_3              int8
jobsickleave_4              int8
jobsickleave_888            int8
jobsickleave_999            int8
jobpension              category
jobtaxes                category
jobmedcare              category
jobsocialsec            category
jobwhere                category
jobpeople                float64
jobtraining             category
trainingmonths           float64
trainingweeks            float64
trainingdays             float64
trainingtype              object
trainingtype_1              int8
trainingtype_2              int8
trainingtype_3              int8
trainingtype_4              int8
trainingtype_5              int8
trainingtype_6              int8
trainingtype_7              int8
trainingtype_8              int8
trainingtype_9              int8
trainingtype_666            int8
trainingtype_888            int8
trainingtype_999            int8
trainingtypeother         object
trainingpaid            category
trainingpaidother         object
traininglose            category
traininglosewhat         float64
dtype: object

In [106]:
df_employment.isnull().sum()

FPrimary                   0
index                      0
hhmid                      0
age                        0
interviewedid              3
paidemployed               3
maintasks                  3
taskdescription            0
taskcode                   0
maintrade                  0
tradecode                  0
joblengthyears             7
joblengthmonths           62
jobweeksperyear           28
jobdaysperweek             5
jobhoursperday            14
last7daysperweek           5
last7hoursperday          14
paid                       3
paidamount               132
paidperiod                70
paidperiodother            0
paidother                  3
paidothervalue          1295
paidotherperiod         1290
paidotherperiodother       0
contract                   3
unionyesno                 3
jobholidays                3
jobsickleave               0
jobsickleave_0             0
jobsickleave_1             0
jobsickleave_2             0
jobsickleave_3             0
jobsickleave_4             0
jobsickleave_888           0
jobsickleave_999           0
jobpension                 3
jobtaxes                   3
jobmedcare                 3
jobsocialsec               3
jobwhere                   3
jobpeople                 92
jobtraining                3
trainingmonths          1289
trainingweeks           1289
trainingdays            1290
trainingtype               0
trainingtype_1             0
trainingtype_2             0
trainingtype_3             0
trainingtype_4             0
trainingtype_5             0
trainingtype_6             0
trainingtype_7             0
trainingtype_8             0
trainingtype_9             0
trainingtype_666           0
trainingtype_888           0
trainingtype_999           0
trainingtypeother          0
trainingpaid            1288
trainingpaidother          0
traininglose            1288
traininglosewhat        1478
dtype: int64

In [96]:
print("Number of rows:", df_gen_ed.shape[0])
print("Number of columns:", df_gen_ed.shape[1])
print("Column names:")
print("\n".join(df_gen_ed.columns))
print("Total data points:", df_gen_ed.shape[0] * df_gen_ed.shape[1])
print(df_gen_ed.dtypes)

Number of rows: 19006
Number of columns: 91
Column names:
FPrimary
index
hhmid
age
relationship
new_mem
interviewedid
attended
highestgrade
highestqual
highestqualother
attendedlast12
attendingstill
currentgrade
schooltype
schoolcode
travelschoolhours
travelschoolminutes
classhours
classminutes
missedhours
missedminutes
homeworkhours
homeworkminutes
expendbreakdown
last12schoolfees
last12pta
last12uniforms
last12books
last12transport
last12foodboard
last12extraclass
last12inkind
last12totalexpend
last12estexpend
whopaid
last12scholarship
last12scholarshipamt
booksaccess
bookshow
bookshow_1
bookshow_2
bookshow_3
bookshow_4
bookshow_5
bookshow_6
bookshow_666
bookshow_888
bookshow_999
bookshowother
feedingprogram
mealsatschool
meal_index_1
meal_name_1
mealsatschoolperweek_1
meal_index_2
meal_name_2
mealsatschoolperweek_2
meal_index_3
meal_name_3
mealsatschoolperweek_3
meal_index_4
meal_name_4
mealsatschoolperweek_4
schooltransport
schooltransportother
oneteacher
teacherabsent
englangteacherabsent
mathteacherabsent
repeatgradeever
repeatgradetimes
skipgradeever
skipgradetimes
apply_secondary
apply_program
apply_program_1
apply_program_2
apply_program_3
apply_program_4
apply_program_5
apply_program_6
apply_program_666
apply_program_888
apply_program_999
apply_programother
admitted_secondary
admitted_program
admitted_programother
ideal_program
ideal_programother
Total data points: 1729546
FPrimary                    object
index                         int8
hhmid                         int8
age                          int16
relationship                  int8
new_mem                    float64
interviewedid             category
attended                  category
highestgrade              category
highestqual               category
highestqualother            object
attendedlast12            category
attendingstill            category
currentgrade              category
schooltype                category
schoolcode                  object
travelschoolhours          float64
travelschoolminutes        float64
classhours                 float64
classminutes               float64
missedhours                float64
missedminutes              float64
homeworkhours              float64
homeworkminutes            float64
expendbreakdown           category
last12schoolfees           float32
last12pta                  float32
last12uniforms             float32
last12books                float32
last12transport            float32
last12foodboard            float32
last12extraclass           float32
last12inkind               float32
last12totalexpend          float64
last12estexpend            float32
whopaid                   category
last12scholarship         category
last12scholarshipamt       float64
booksaccess               category
bookshow                    object
bookshow_1                    int8
bookshow_2                    int8
bookshow_3                    int8
bookshow_4                    int8
bookshow_5                    int8
bookshow_6                    int8
bookshow_666                  int8
bookshow_888                  int8
bookshow_999                  int8
bookshowother               object
feedingprogram            category
mealsatschool               object
meal_index_1               float64
meal_name_1                 object
mealsatschoolperweek_1     float64
meal_index_2               float64
meal_name_2                 object
mealsatschoolperweek_2     float64
meal_index_3               float64
meal_name_3                 object
mealsatschoolperweek_3     float64
meal_index_4               float64
meal_name_4                 object
mealsatschoolperweek_4     float64
schooltransport           category
schooltransportother        object
oneteacher                category
teacherabsent              float64
englangteacherabsent       float64
mathteacherabsent          float64
repeatgradeever           category
repeatgradetimes           float64
skipgradeever             category
skipgradetimes             float64
apply_secondary           category
apply_program               object
apply_program_1               int8
apply_program_2               int8
apply_program_3               int8
apply_program_4               int8
apply_program_5               int8
apply_program_6               int8
apply_program_666             int8
apply_program_888             int8
apply_program_999             int8
apply_programother          object
admitted_secondary        category
admitted_program          category
admitted_programother       object
ideal_program             category
ideal_programother          object
dtype: object

In [94]:
df_gen_ed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19006 entries, 0 to 19005
Data columns (total 91 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   FPrimary                19006 non-null  object
 1   index                   19006 non-null  int8
 2   hhmid                   19006 non-null  int8
 3   age                     19006 non-null  int16
 4   relationship            19006 non-null  int8
 5   new_mem                 19004 non-null  float64
 6   interviewedid           19003 non-null  category
 7   attended                17931 non-null  category
 8   highestgrade            13738 non-null  category
 9   highestqual             13739 non-null  category
 10  highestqualother        19006 non-null  object
 11  attendedlast12          13761 non-null  category
 12  attendingstill          6508 non-null   category
 13  currentgrade            6100 non-null   category
 14  schooltype              6102 non-null   category
 15  schoolcode              19006 non-null  object
 16  travelschoolhours       5439 non-null   float64
 17  travelschoolminutes     5421 non-null   float64
 18  classhours              4189 non-null   float64
 19  classminutes            4146 non-null   float64
 20  missedhours             4158 non-null   float64
 21  missedminutes           4163 non-null   float64
 22  homeworkhours           5095 non-null   float64
 23  homeworkminutes         5126 non-null   float64
 24  expendbreakdown         6508 non-null   category
 25  last12schoolfees        2622 non-null   float32
 26  last12pta               2622 non-null   float32
 27  last12uniforms          2622 non-null   float32
 28  last12books             2622 non-null   float32
 29  last12transport         2622 non-null   float32
 30  last12foodboard         2622 non-null   float32
 31  last12extraclass        2622 non-null   float32
 32  last12inkind            2622 non-null   float32
 33  last12totalexpend       2622 non-null   float64
 34  last12estexpend         3886 non-null   float32
 35  whopaid                 6505 non-null   category
 36  last12scholarship       6508 non-null   category
 37  last12scholarshipamt    51 non-null     float64
 38  booksaccess             6479 non-null   category
 39  bookshow                19006 non-null  object
 40  bookshow_1              19006 non-null  int8
 41  bookshow_2              19006 non-null  int8
 42  bookshow_3              19006 non-null  int8
 43  bookshow_4              19006 non-null  int8
 44  bookshow_5              19006 non-null  int8
 45  bookshow_6              19006 non-null  int8
 46  bookshow_666            19006 non-null  int8
 47  bookshow_888            19006 non-null  int8
 48  bookshow_999            19006 non-null  int8
 49  bookshowother           19006 non-null  object
 50  feedingprogram          6113 non-null   category
 51  mealsatschool           19006 non-null  object
 52  meal_index_1            1718 non-null   float64
 53  meal_name_1             19006 non-null  object
 54  mealsatschoolperweek_1  1683 non-null   float64
 55  meal_index_2            205 non-null    float64
 56  meal_name_2             19006 non-null  object
 57  mealsatschoolperweek_2  194 non-null    float64
 58  meal_index_3            197 non-null    float64
 59  meal_name_3             19006 non-null  object
 60  mealsatschoolperweek_3  186 non-null    float64
 61  meal_index_4            5 non-null      float64
 62  meal_name_4             19006 non-null  object
 63  mealsatschoolperweek_4  5 non-null      float64
 64  schooltransport         6505 non-null   category
 65  schooltransportother    19006 non-null  object
 66  oneteacher              6508 non-null   category
 67  teacherabsent           2917 non-null   float64
 68  englangteacherabsent    2247 non-null   float64
 69  mathteacherabsent       2245 non-null   float64
 70  repeatgradeever         13761 non-null  category
 71  repeatgradetimes        1707 non-null   float64
 72  skipgradeever           13761 non-null  category
 73  skipgradetimes          421 non-null    float64
 74  apply_secondary         4268 non-null   category
 75  apply_program           19006 non-null  object
 76  apply_program_1         19006 non-null  int8
 77  apply_program_2         19006 non-null  int8
 78  apply_program_3         19006 non-null  int8
 79  apply_program_4         19006 non-null  int8
 80  apply_program_5         19006 non-null  int8
 81  apply_program_6         19006 non-null  int8
 82  apply_program_666       19006 non-null  int8
 83  apply_program_888       19006 non-null  int8
 84  apply_program_999       19006 non-null  int8
 85  apply_programother      19006 non-null  object
 86  admitted_secondary      641 non-null    category
 87  admitted_program        416 non-null    category
 88  admitted_programother   19006 non-null  object
 89  ideal_program           3689 non-null   category
 90  ideal_programother      19006 non-null  object
dtypes: category(21), float32(9), float64(24), int16(1), int8(21), object(15)
memory usage: 7.1+ MB

In [107]:
df_gen_ed.isnull().sum()

FPrimary                      0
index                         0
hhmid                         0
age                           0
relationship                  0
new_mem                       2
interviewedid                 3
attended                   1075
highestgrade               5268
highestqual                5267
highestqualother              0
attendedlast12             5245
attendingstill            12498
currentgrade              12906
schooltype                12904
schoolcode                    0
travelschoolhours         13567
travelschoolminutes       13585
classhours                14817
classminutes              14860
missedhours               14848
missedminutes             14843
homeworkhours             13911
homeworkminutes           13880
expendbreakdown           12498
last12schoolfees          16384
last12pta                 16384
last12uniforms            16384
last12books               16384
last12transport           16384
last12foodboard           16384
last12extraclass          16384
last12inkind              16384
last12totalexpend         16384
last12estexpend           15120
whopaid                   12501
last12scholarship         12498
last12scholarshipamt      18955
booksaccess               12527
bookshow                      0
bookshow_1                    0
bookshow_2                    0
bookshow_3                    0
bookshow_4                    0
bookshow_5                    0
bookshow_6                    0
bookshow_666                  0
bookshow_888                  0
bookshow_999                  0
bookshowother                 0
feedingprogram            12893
mealsatschool                 0
meal_index_1              17288
meal_name_1                   0
mealsatschoolperweek_1    17323
meal_index_2              18801
meal_name_2                   0
mealsatschoolperweek_2    18812
meal_index_3              18809
meal_name_3                   0
mealsatschoolperweek_3    18820
meal_index_4              19001
meal_name_4                   0
mealsatschoolperweek_4    19001
schooltransport           12501
schooltransportother          0
oneteacher                12498
teacherabsent             16089
englangteacherabsent      16759
mathteacherabsent         16761
repeatgradeever            5245
repeatgradetimes          17299
skipgradeever              5245
skipgradetimes            18585
apply_secondary           14738
apply_program                 0
apply_program_1               0
apply_program_2               0
apply_program_3               0
apply_program_4               0
apply_program_5               0
apply_program_6               0
apply_program_666             0
apply_program_888             0
apply_program_999             0
apply_programother            0
admitted_secondary        18365
admitted_program          18590
admitted_programother         0
ideal_program             15317
ideal_programother            0
dtype: int64

# Table Summaries

## **Background - Demographics Table**

In [110]:
import pandas as pd
df = pd.read_stata('2025-HUDS-Bootcamp/Data/THREADS/Wave_3/01d_background.dta')
df.head(30)
df.tail(30)
print(df.dtypes)

FPrimary                  object
index                       int8
hhmid                       int8
age                        int16
maritalstatus           category
new_mem                  float64
interviewedid           category
spouseinhouse           category
spouseindex_1            float64
spouseid_1               float64
spouseindex_2            float64
spouseid_2               float64
spouseindex_3            float64
spouseid_3               float64
agemarried               float64
yearmarried              float64
dowrygiven               float32
dowrygivencedis         category
dowrygivenother           object
dowryreceived            float32
dowryreceivedcedis      category
dowryreceivedother        object
ceremony                 float32
ceremonycedis           category
ceremonyother             object
religion                category
religionother             object
christian_denom         category
christian_denomother      object
muslim_denom            category
muslim_denomother         object
whereborn_region        category
whereborn_district        object
whereborn_country         object
nationality             category
nationalityother          object
ethnicity               category
ethnicityother            object
fatherinhouse           category
fatherid                 float64
fathereduc              category
fathereducother           object
fatherwork              category
motherinhouse           category
motherid                 float64
mothereduc              category
mothereducother           object
motherwork              category
politicaloffice         category
stillpoloffice          category
traditionaloffice       category
stilltradoffice         category
awaylast12               float64
movereason              category
movereasonother           object
movewhere_region        category
movewhere_district        object
movewhere_country         object
dtype: object

## Education Beliefs (pre) Table

In [114]:
import pandas as pd
df_edu_belief = pd.read_stata('2025-HUDS-Bootcamp/Data/THREADS/Wave_3/01giv_education_beliefs_pre.dta')
df_edu_belief.head()
df_edu_belief.tail(30)
df_edu_belief.info()
print(df_edu_belief.dtypes)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4807 entries, 0 to 4806
Columns: 1240 entries, FPrimary to endtime
dtypes: category(871), float32(5), float64(309), object(55)
memory usage: 17.6+ MB
FPrimary                        object
child_count                    float64
child_ind_join                  object
young_child_count              float64
young_child_ind_join            object
treatment                     category
starttime                       object
materials_have                category
planners_have                 category
parent                        category
mother                        category
mother_available              category
father                        category
father_available              category
parent_treat_yn                float64
parent_index_1                 float64
parent_treat_1                 float64
earnings_math_pb_1            category
earnings_nonmath_pb_1         category
earnings_noattend_pb_1        category
earnings_math_pg_1            category
earnings_nonmath_pg_1         category
earnings_noattend_pg_1        category
occupation_math_pb_1          category
occupation_nonmath_pb_1       category
occupation_noattend_pb_1      category
occupation_math_pg_1          category
occupation_nonmath_pg_1       category
occupation_noattend_pg_1      category
marriage_math_pb_1            category
marriage_nonmath_pb_1         category
marriage_noattend_pb_1        category
marriage_math_pg_1            category
marriage_nonmath_pg_1         category
marriage_noattend_pg_1        category
children_math_pb_1            category
children_nonmath_pb_1         category
children_noattend_pb_1        category
children_math_pg_1            category
children_nonmath_pg_1         category
children_noattend_pg_1        category
spouse_math_pb_1              category
spouse_nonmath_pb_1           category
spouse_noattend_pb_1          category
spouse_math_pg_1              category
spouse_nonmath_pg_1           category
spouse_noattend_pg_1          category
math_school_p_1               category
math_domestic_p_1             category
boys_gifted_math_p_1          category
boys_giftedenglish_p_1        category
girls_domesticskills_p_1      category
girls_parenting_p_1           category
career_math_p_1               category
career_english_p_1            category
index_p_1_1                    float64
temp_index_p_1_1               float64
separate_note_p_1_1           category
math_rank_p_1_1               category
english_rank_p_1_1            category
math_predict_p_1_1            category
math_prize_p_1_1              category
english_predict_p_1_1         category
english_prize_p_1_1           category
pastmathbook_cost_p_1_1        float32
pastenglishbook_cost_p_1_1     float32
pastedu_talk_p_1_1            category
pastmath_talk_p_1_1           category
mathbook_cost_p_1_1           category
englishbook_cost_p_1_1        category
math_hw_hrs_p_1_1             category
math_hw_mins_p_1_1            category
english_hw_hrs_p_1_1          category
english_hw_mins_p_1_1         category
edu_talk_p_1_1                category
math_talk_p_1_1               category
attend_secondary_p_1_1        category
study_secondary_p_1_1         category
study_secondary_p_osp_1_1       object
likely_attend_p_1_1           category
likely_study_p_1_1            category
likely_study_p_osp_1_1          object
index_p_1_2                    float64
temp_index_p_1_2               float64
separate_note_p_1_2           category
math_rank_p_1_2               category
english_rank_p_1_2            category
math_predict_p_1_2            category
math_prize_p_1_2              category
english_predict_p_1_2         category
english_prize_p_1_2           category
pastmathbook_cost_p_1_2        float64
pastenglishbook_cost_p_1_2     float64
pastedu_talk_p_1_2            category
pastmath_talk_p_1_2           category
mathbook_cost_p_1_2           category
englishbook_cost_p_1_2        category
math_hw_hrs_p_1_2             category
math_hw_mins_p_1_2            category
english_hw_hrs_p_1_2          category
english_hw_mins_p_1_2         category
edu_talk_p_1_2                category
math_talk_p_1_2               category
attend_secondary_p_1_2        category
study_secondary_p_1_2          float64
study_secondary_p_osp_1_2       object
likely_attend_p_1_2           category
likely_study_p_1_2             float64
likely_study_p_osp_1_2          object
index_p_1_3                    float64
temp_index_p_1_3               float64
separate_note_p_1_3           category
math_rank_p_1_3               category
english_rank_p_1_3            category
math_predict_p_1_3            category
math_prize_p_1_3              category
english_predict_p_1_3         category
english_prize_p_1_3           category
pastmathbook_cost_p_1_3        float64
pastenglishbook_cost_p_1_3     float64
pastedu_talk_p_1_3            category
pastmath_talk_p_1_3           category
mathbook_cost_p_1_3           category
englishbook_cost_p_1_3        category
math_hw_hrs_p_1_3             category
math_hw_mins_p_1_3            category
english_hw_hrs_p_1_3          category
english_hw_mins_p_1_3         category
edu_talk_p_1_3                category
math_talk_p_1_3               category
attend_secondary_p_1_3        category
study_secondary_p_1_3          float64
study_secondary_p_osp_1_3       object
likely_attend_p_1_3           category
likely_study_p_1_3             float64
likely_study_p_osp_1_3          object
index_p_1_4                    float64
temp_index_p_1_4               float64
separate_note_p_1_4           category
math_rank_p_1_4               category
english_rank_p_1_4            category
math_predict_p_1_4            category
math_prize_p_1_4              category
english_predict_p_1_4         category
english_prize_p_1_4           category
pastmathbook_cost_p_1_4        float64
pastenglishbook_cost_p_1_4     float64
pastedu_talk_p_1_4            category
pastmath_talk_p_1_4           category
mathbook_cost_p_1_4           category
englishbook_cost_p_1_4        category
math_hw_hrs_p_1_4             category
math_hw_mins_p_1_4            category
english_hw_hrs_p_1_4          category
english_hw_mins_p_1_4         category
edu_talk_p_1_4                category
math_talk_p_1_4               category
attend_secondary_p_1_4        category
study_secondary_p_1_4          float64
study_secondary_p_osp_1_4       object
likely_attend_p_1_4           category
likely_study_p_1_4             float64
likely_study_p_osp_1_4          object
index_p_1_5                    float64
temp_index_p_1_5               float64
separate_note_p_1_5           category
math_rank_p_1_5               category
english_rank_p_1_5            category
math_predict_p_1_5            category
math_prize_p_1_5              category
english_predict_p_1_5         category
english_prize_p_1_5           category
pastmathbook_cost_p_1_5        float64
pastenglishbook_cost_p_1_5     float64
pastedu_talk_p_1_5            category
pastmath_talk_p_1_5           category
mathbook_cost_p_1_5           category
englishbook_cost_p_1_5        category
math_hw_hrs_p_1_5             category
math_hw_mins_p_1_5            category
english_hw_hrs_p_1_5          category
english_hw_mins_p_1_5         category
edu_talk_p_1_5                category
math_talk_p_1_5               category
attend_secondary_p_1_5        category
study_secondary_p_1_5          float64
study_secondary_p_osp_1_5       object
likely_attend_p_1_5           category
likely_study_p_1_5             float64
likely_study_p_osp_1_5          object
index_p_1_6                    float64
temp_index_p_1_6               float64
separate_note_p_1_6           category
math_rank_p_1_6               category
english_rank_p_1_6            category
math_predict_p_1_6            category
math_prize_p_1_6              category
english_predict_p_1_6         category
english_prize_p_1_6           category
pastmathbook_cost_p_1_6        float64
pastenglishbook_cost_p_1_6     float64
pastedu_talk_p_1_6            category
pastmath_talk_p_1_6           category
mathbook_cost_p_1_6           category
englishbook_cost_p_1_6        category
math_hw_hrs_p_1_6             category
math_hw_mins_p_1_6            category
english_hw_hrs_p_1_6          category
english_hw_mins_p_1_6         category
edu_talk_p_1_6                category
math_talk_p_1_6               category
attend_secondary_p_1_6        category
study_secondary_p_1_6          float64
study_secondary_p_osp_1_6       object
likely_attend_p_1_6           category
likely_study_p_1_6             float64
likely_study_p_osp_1_6          object
index_p_1_7                    float64
temp_index_p_1_7               float64
separate_note_p_1_7           category
math_rank_p_1_7               category
english_rank_p_1_7            category
math_predict_p_1_7            category
math_prize_p_1_7              category
english_predict_p_1_7         category
english_prize_p_1_7           category
pastmathbook_cost_p_1_7        float64
pastenglishbook_cost_p_1_7     float64
pastedu_talk_p_1_7            category
pastmath_talk_p_1_7           category
mathbook_cost_p_1_7           category
englishbook_cost_p_1_7        category
math_hw_hrs_p_1_7             category
math_hw_mins_p_1_7            category
english_hw_hrs_p_1_7          category
english_hw_mins_p_1_7         category
edu_talk_p_1_7                category
math_talk_p_1_7               category
attend_secondary_p_1_7        category
study_secondary_p_1_7          float64
study_secondary_p_osp_1_7       object
likely_attend_p_1_7           category
likely_study_p_1_7             float64
likely_study_p_osp_1_7          object
index_p_1_8                    float64
temp_index_p_1_8               float64
separate_note_p_1_8           category
math_rank_p_1_8               category
english_rank_p_1_8            category
math_predict_p_1_8            category
math_prize_p_1_8              category
english_predict_p_1_8         category
english_prize_p_1_8           category
pastmathbook_cost_p_1_8        float64
pastenglishbook_cost_p_1_8     float64
pastedu_talk_p_1_8            category
pastmath_talk_p_1_8           category
mathbook_cost_p_1_8           category
englishbook_cost_p_1_8        category
math_hw_hrs_p_1_8             category
math_hw_mins_p_1_8            category
english_hw_hrs_p_1_8          category
english_hw_mins_p_1_8         category
edu_talk_p_1_8                category
math_talk_p_1_8               category
attend_secondary_p_1_8        category
study_secondary_p_1_8          float64
study_secondary_p_osp_1_8       object
likely_attend_p_1_8           category
likely_study_p_1_8             float64
likely_study_p_osp_1_8          object
ready_yn_p_1                  category
index_1_1                      float64
temp_index_1_1                 float64
temp_highestgrade_1_1          float64
temp_currentgrade_1_1          float64
temp_math_score_1_1            float64
temp_english_score_1_1         float64
child_math_score_1_1           float64
child_eng_score_1_1            float64
planner_type_1_1              category
index_1_2                      float64
temp_index_1_2                 float64
temp_highestgrade_1_2          float64
temp_currentgrade_1_2          float64
temp_math_score_1_2            float64
temp_english_score_1_2         float64
child_math_score_1_2           float64
child_eng_score_1_2            float64
planner_type_1_2              category
index_1_3                      float64
temp_index_1_3                 float64
temp_highestgrade_1_3          float64
temp_currentgrade_1_3          float64
temp_math_score_1_3            float64
temp_english_score_1_3         float64
child_math_score_1_3           float64
child_eng_score_1_3            float64
planner_type_1_3              category
index_1_4                      float64
temp_index_1_4                 float64
temp_highestgrade_1_4          float64
temp_currentgrade_1_4          float64
temp_math_score_1_4            float64
temp_english_score_1_4         float64
child_math_score_1_4           float64
child_eng_score_1_4            float64
planner_type_1_4              category
index_1_5                      float64
temp_index_1_5                 float64
temp_highestgrade_1_5          float64
temp_currentgrade_1_5          float64
temp_math_score_1_5            float64
temp_english_score_1_5         float64
child_math_score_1_5           float64
child_eng_score_1_5            float64
planner_type_1_5              category
index_1_6                      float64
temp_index_1_6                 float64
temp_highestgrade_1_6          float64
temp_currentgrade_1_6          float64
temp_math_score_1_6            float64
temp_english_score_1_6         float64
child_math_score_1_6           float64
child_eng_score_1_6            float64
planner_type_1_6              category
index_1_7                      float64
temp_index_1_7                 float64
temp_highestgrade_1_7          float64
temp_currentgrade_1_7          float64
temp_math_score_1_7            float64
temp_english_score_1_7         float64
child_math_score_1_7           float64
child_eng_score_1_7            float64
planner_type_1_7              category
index_1_8                      float64
temp_index_1_8                 float64
temp_highestgrade_1_8          float64
temp_currentgrade_1_8          float64
temp_math_score_1_8            float64
temp_english_score_1_8         float64
child_math_score_1_8           float64
child_eng_score_1_8            float64
planner_type_1_8              category
parent_index_2                 float64
parent_treat_2                 float64
earnings_math_pb_2            category
earnings_nonmath_pb_2         category
earnings_noattend_pb_2        category
earnings_math_pg_2            category
earnings_nonmath_pg_2         category
earnings_noattend_pg_2        category
occupation_math_pb_2          category
occupation_nonmath_pb_2       category
occupation_noattend_pb_2      category
occupation_math_pg_2          category
occupation_nonmath_pg_2       category
occupation_noattend_pg_2      category
marriage_math_pb_2            category
marriage_nonmath_pb_2         category
marriage_noattend_pb_2        category
marriage_math_pg_2            category
marriage_nonmath_pg_2         category
marriage_noattend_pg_2        category
children_math_pb_2            category
children_nonmath_pb_2         category
children_noattend_pb_2        category
children_math_pg_2            category
children_nonmath_pg_2         category
children_noattend_pg_2        category
spouse_math_pb_2              category
spouse_nonmath_pb_2           category
spouse_noattend_pb_2          category
spouse_math_pg_2              category
spouse_nonmath_pg_2           category
spouse_noattend_pg_2          category
math_school_p_2               category
math_domestic_p_2             category
boys_gifted_math_p_2          category
boys_giftedenglish_p_2        category
girls_domesticskills_p_2      category
girls_parenting_p_2           category
career_math_p_2               category
career_english_p_2            category
index_p_2_1                    float64
temp_index_p_2_1               float64
separate_note_p_2_1           category
math_rank_p_2_1               category
english_rank_p_2_1            category
math_predict_p_2_1            category
math_prize_p_2_1              category
english_predict_p_2_1         category
english_prize_p_2_1           category
pastmathbook_cost_p_2_1        float32
pastenglishbook_cost_p_2_1     float32
pastedu_talk_p_2_1            category
pastmath_talk_p_2_1           category
mathbook_cost_p_2_1           category
englishbook_cost_p_2_1        category
math_hw_hrs_p_2_1             category
math_hw_mins_p_2_1            category
english_hw_hrs_p_2_1          category
english_hw_mins_p_2_1         category
edu_talk_p_2_1                category
math_talk_p_2_1               category
attend_secondary_p_2_1        category
study_secondary_p_2_1          float64
study_secondary_p_osp_2_1       object
likely_attend_p_2_1           category
likely_study_p_2_1             float64
likely_study_p_osp_2_1          object
index_p_2_2                    float64
temp_index_p_2_2               float64
separate_note_p_2_2           category
math_rank_p_2_2               category
english_rank_p_2_2            category
math_predict_p_2_2            category
math_prize_p_2_2              category
english_predict_p_2_2         category
english_prize_p_2_2           category
pastmathbook_cost_p_2_2        float32
pastenglishbook_cost_p_2_2     float64
pastedu_talk_p_2_2            category
pastmath_talk_p_2_2           category
mathbook_cost_p_2_2           category
englishbook_cost_p_2_2        category
math_hw_hrs_p_2_2             category
math_hw_mins_p_2_2            category
english_hw_hrs_p_2_2          category
english_hw_mins_p_2_2         category
edu_talk_p_2_2                category
math_talk_p_2_2               category
attend_secondary_p_2_2        category
study_secondary_p_2_2          float64
study_secondary_p_osp_2_2       object
likely_attend_p_2_2           category
likely_study_p_2_2             float64
likely_study_p_osp_2_2          object
index_p_2_3                    float64
temp_index_p_2_3               float64
separate_note_p_2_3           category
math_rank_p_2_3               category
english_rank_p_2_3            category
math_predict_p_2_3            category
math_prize_p_2_3              category
english_predict_p_2_3         category
english_prize_p_2_3           category
pastmathbook_cost_p_2_3        float64
pastenglishbook_cost_p_2_3     float64
pastedu_talk_p_2_3            category
pastmath_talk_p_2_3           category
mathbook_cost_p_2_3           category
englishbook_cost_p_2_3        category
math_hw_hrs_p_2_3             category
math_hw_mins_p_2_3            category
english_hw_hrs_p_2_3          category
english_hw_mins_p_2_3         category
edu_talk_p_2_3                category
math_talk_p_2_3               category
attend_secondary_p_2_3        category
study_secondary_p_2_3          float64
study_secondary_p_osp_2_3       object
likely_attend_p_2_3           category
likely_study_p_2_3             float64
likely_study_p_osp_2_3          object
index_p_2_4                    float64
temp_index_p_2_4               float64
separate_note_p_2_4           category
math_rank_p_2_4               category
english_rank_p_2_4            category
math_predict_p_2_4            category
math_prize_p_2_4              category
english_predict_p_2_4         category
english_prize_p_2_4           category
pastmathbook_cost_p_2_4        float64
pastenglishbook_cost_p_2_4     float64
pastedu_talk_p_2_4            category
pastmath_talk_p_2_4           category
mathbook_cost_p_2_4           category
englishbook_cost_p_2_4        category
math_hw_hrs_p_2_4             category
math_hw_mins_p_2_4            category
english_hw_hrs_p_2_4          category
english_hw_mins_p_2_4         category
edu_talk_p_2_4                category
math_talk_p_2_4               category
attend_secondary_p_2_4        category
study_secondary_p_2_4          float64
study_secondary_p_osp_2_4       object
likely_attend_p_2_4           category
likely_study_p_2_4             float64
likely_study_p_osp_2_4          object
index_p_2_5                    float64
temp_index_p_2_5               float64
separate_note_p_2_5           category
math_rank_p_2_5               category
english_rank_p_2_5            category
math_predict_p_2_5            category
math_prize_p_2_5              category
english_predict_p_2_5         category
english_prize_p_2_5           category
pastmathbook_cost_p_2_5        float64
pastenglishbook_cost_p_2_5     float64
pastedu_talk_p_2_5            category
pastmath_talk_p_2_5           category
mathbook_cost_p_2_5           category
englishbook_cost_p_2_5        category

In [116]:
df_edu_belief.isnull().sum()

FPrimary                         0
child_count                     58
child_ind_join                   0
young_child_count               58
young_child_ind_join             0
treatment                     2966
starttime                        0
materials_have                3332
planners_have                 3332
parent                        3332
mother                        3425
mother_available              3425
father                        3715
father_available              3715
parent_treat_yn               3332
parent_index_1                3340
parent_treat_1                3340
earnings_math_pb_1            3409
earnings_nonmath_pb_1         3409
earnings_noattend_pb_1        3422
earnings_math_pg_1            3408
earnings_nonmath_pg_1         3407
earnings_noattend_pg_1        3422
occupation_math_pb_1          3357
occupation_nonmath_pb_1       3360
occupation_noattend_pb_1      3363
occupation_math_pg_1          3359
occupation_nonmath_pg_1       3361
occupation_noattend_pg_1      3367
marriage_math_pb_1            3366
marriage_nonmath_pb_1         3365
marriage_noattend_pb_1        3369
marriage_math_pg_1            3364
marriage_nonmath_pg_1         3366
marriage_noattend_pg_1        3361
children_math_pb_1            3372
children_nonmath_pb_1         3373
children_noattend_pb_1        3373
children_math_pg_1            3373
children_nonmath_pg_1         3374
children_noattend_pg_1        3378
spouse_math_pb_1              3425
spouse_nonmath_pb_1           3427
spouse_noattend_pb_1          3431
spouse_math_pg_1              3426
spouse_nonmath_pg_1           3429
spouse_noattend_pg_1          3433
math_school_p_1               3360
math_domestic_p_1             3353
boys_gifted_math_p_1          3370
boys_giftedenglish_p_1        3370
girls_domesticskills_p_1      3356
girls_parenting_p_1           3353
career_math_p_1               3364
career_english_p_1            3366
index_p_1_1                   3340
temp_index_p_1_1              3340
separate_note_p_1_1           4088
math_rank_p_1_1               3390
english_rank_p_1_1            3391
math_predict_p_1_1            3389
math_prize_p_1_1              3386
english_predict_p_1_1         3389
english_prize_p_1_1           3386
pastmathbook_cost_p_1_1       3431
pastenglishbook_cost_p_1_1    3431
pastedu_talk_p_1_1            3364
pastmath_talk_p_1_1           3371
mathbook_cost_p_1_1           3432
englishbook_cost_p_1_1        3430
math_hw_hrs_p_1_1             3425
math_hw_mins_p_1_1            3427
english_hw_hrs_p_1_1          3425
english_hw_mins_p_1_1         3427
edu_talk_p_1_1                3417
math_talk_p_1_1               3424
attend_secondary_p_1_1        3340
study_secondary_p_1_1         3521
study_secondary_p_osp_1_1        0
likely_attend_p_1_1           3369
likely_study_p_1_1            3619
likely_study_p_osp_1_1           0
index_p_1_2                   4021
temp_index_p_1_2              4040
separate_note_p_1_2           4440
math_rank_p_1_2               4041
english_rank_p_1_2            4041
math_predict_p_1_2            4045
math_prize_p_1_2              4043
english_predict_p_1_2         4043
english_prize_p_1_2           4044
pastmathbook_cost_p_1_2       4076
pastenglishbook_cost_p_1_2    4076
pastedu_talk_p_1_2            4033
pastmath_talk_p_1_2           4035
mathbook_cost_p_1_2           4063
englishbook_cost_p_1_2        4063
math_hw_hrs_p_1_2             4062
math_hw_mins_p_1_2            4062
english_hw_hrs_p_1_2          4062
english_hw_mins_p_1_2         4064
edu_talk_p_1_2                4061
math_talk_p_1_2               4064
attend_secondary_p_1_2        4021
study_secondary_p_1_2         4129
study_secondary_p_osp_1_2        0
likely_attend_p_1_2           4045
likely_study_p_1_2            4180
likely_study_p_osp_1_2           0
index_p_1_3                   4514
temp_index_p_1_3              4531
separate_note_p_1_3           4670
math_rank_p_1_3               4529
english_rank_p_1_3            4531
math_predict_p_1_3            4530
math_prize_p_1_3              4528
english_predict_p_1_3         4531
english_prize_p_1_3           4527
pastmathbook_cost_p_1_3       4536
pastenglishbook_cost_p_1_3    4536
pastedu_talk_p_1_3            4523
pastmath_talk_p_1_3           4525
mathbook_cost_p_1_3           4540
englishbook_cost_p_1_3        4540
math_hw_hrs_p_1_3             4539
math_hw_mins_p_1_3            4539
english_hw_hrs_p_1_3          4540
english_hw_mins_p_1_3         4540
edu_talk_p_1_3                4540
math_talk_p_1_3               4540
attend_secondary_p_1_3        4514
study_secondary_p_1_3         4562
study_secondary_p_osp_1_3        0
likely_attend_p_1_3           4533
likely_study_p_1_3            4580
likely_study_p_osp_1_3           0
index_p_1_4                   4720
temp_index_p_1_4              4723
separate_note_p_1_4           4758
math_rank_p_1_4               4725
english_rank_p_1_4            4726
math_predict_p_1_4            4726
math_prize_p_1_4              4727
english_predict_p_1_4         4727
english_prize_p_1_4           4727
pastmathbook_cost_p_1_4       4725
pastenglishbook_cost_p_1_4    4725
pastedu_talk_p_1_4            4725
pastmath_talk_p_1_4           4725
mathbook_cost_p_1_4           4734
englishbook_cost_p_1_4        4734
math_hw_hrs_p_1_4             4734
math_hw_mins_p_1_4            4734
english_hw_hrs_p_1_4          4734
english_hw_mins_p_1_4         4734
edu_talk_p_1_4                4734
math_talk_p_1_4               4734
attend_secondary_p_1_4        4720
study_secondary_p_1_4         4739
study_secondary_p_osp_1_4        0
likely_attend_p_1_4           4726
likely_study_p_1_4            4748
likely_study_p_osp_1_4           0
index_p_1_5                   4781
temp_index_p_1_5              4783
separate_note_p_1_5           4794
math_rank_p_1_5               4785
english_rank_p_1_5            4785
math_predict_p_1_5            4786
math_prize_p_1_5              4786
english_predict_p_1_5         4786
english_prize_p_1_5           4786
pastmathbook_cost_p_1_5       4781
pastenglishbook_cost_p_1_5    4781
pastedu_talk_p_1_5            4784
pastmath_talk_p_1_5           4784
mathbook_cost_p_1_5           4787
englishbook_cost_p_1_5        4787
math_hw_hrs_p_1_5             4787
math_hw_mins_p_1_5            4787
english_hw_hrs_p_1_5          4787
english_hw_mins_p_1_5         4787
edu_talk_p_1_5                4787
math_talk_p_1_5               4788
attend_secondary_p_1_5        4781
study_secondary_p_1_5         4791
study_secondary_p_osp_1_5        0
likely_attend_p_1_5           4784
likely_study_p_1_5            4792
likely_study_p_osp_1_5           0
index_p_1_6                   4800
temp_index_p_1_6              4800
separate_note_p_1_6           4802
math_rank_p_1_6               4800
english_rank_p_1_6            4800
math_predict_p_1_6            4802
math_prize_p_1_6              4802
english_predict_p_1_6         4802
english_prize_p_1_6           4802
pastmathbook_cost_p_1_6       4800
pastenglishbook_cost_p_1_6    4800
pastedu_talk_p_1_6            4801
pastmath_talk_p_1_6           4801
mathbook_cost_p_1_6           4802
englishbook_cost_p_1_6        4802
math_hw_hrs_p_1_6             4802
math_hw_mins_p_1_6            4802
english_hw_hrs_p_1_6          4802
english_hw_mins_p_1_6         4802
edu_talk_p_1_6                4802
math_talk_p_1_6               4802
attend_secondary_p_1_6        4800
study_secondary_p_1_6         4803
study_secondary_p_osp_1_6        0
likely_attend_p_1_6           4802
likely_study_p_1_6            4805
likely_study_p_osp_1_6           0
index_p_1_7                   4803
temp_index_p_1_7              4803
separate_note_p_1_7           4804
math_rank_p_1_7               4803
english_rank_p_1_7            4803
math_predict_p_1_7            4804
math_prize_p_1_7              4804
english_predict_p_1_7         4804
english_prize_p_1_7           4804
pastmathbook_cost_p_1_7       4803
pastenglishbook_cost_p_1_7    4803
pastedu_talk_p_1_7            4804
pastmath_talk_p_1_7           4804
mathbook_cost_p_1_7           4804
englishbook_cost_p_1_7        4804
math_hw_hrs_p_1_7             4804
math_hw_mins_p_1_7            4804
english_hw_hrs_p_1_7          4804
english_hw_mins_p_1_7         4804
edu_talk_p_1_7                4804
math_talk_p_1_7               4804
attend_secondary_p_1_7        4803
study_secondary_p_1_7         4806
study_secondary_p_osp_1_7        0
likely_attend_p_1_7           4804
likely_study_p_1_7            4806
likely_study_p_osp_1_7           0
index_p_1_8                   4805
temp_index_p_1_8              4805
separate_note_p_1_8           4805
math_rank_p_1_8               4805
english_rank_p_1_8            4805
math_predict_p_1_8            4805
math_prize_p_1_8              4805
english_predict_p_1_8         4805
english_prize_p_1_8           4805
pastmathbook_cost_p_1_8       4805
pastenglishbook_cost_p_1_8    4805
pastedu_talk_p_1_8            4805
pastmath_talk_p_1_8           4805
mathbook_cost_p_1_8           4805
englishbook_cost_p_1_8        4805
math_hw_hrs_p_1_8             4805
math_hw_mins_p_1_8            4805
english_hw_hrs_p_1_8          4805
english_hw_mins_p_1_8         4805
edu_talk_p_1_8                4805
math_talk_p_1_8               4805
attend_secondary_p_1_8        4805
study_secondary_p_1_8         4806
study_secondary_p_osp_1_8        0
likely_attend_p_1_8           4805
likely_study_p_1_8            4806
likely_study_p_osp_1_8           0
ready_yn_p_1                  3615
index_1_1                     3661
temp_index_1_1                3661
temp_highestgrade_1_1         3687
temp_currentgrade_1_1         3898
temp_math_score_1_1           3752
temp_english_score_1_1        3752
child_math_score_1_1          3661
child_eng_score_1_1           3661
planner_type_1_1              3661
index_1_2                     4212
temp_index_1_2                4224
temp_highestgrade_1_2         4242
temp_currentgrade_1_2         4308
temp_math_score_1_2           4280
temp_english_score_1_2        4280
child_math_score_1_2          4212
child_eng_score_1_2           4212
planner_type_1_2              4215
index_1_3                     4585
temp_index_1_3                4597
temp_highestgrade_1_3         4610
temp_currentgrade_1_3         4636
temp_math_score_1_3           4629
temp_english_score_1_3        4629
child_math_score_1_3          4585
child_eng_score_1_3           4585
planner_type_1_3              4585
index_1_4                     4744
temp_index_1_4                4745
temp_highestgrade_1_4         4753
temp_currentgrade_1_4         4758
temp_math_score_1_4           4756
temp_english_score_1_4        4756
child_math_score_1_4          4744
child_eng_score_1_4           4744
planner_type_1_4              4744
index_1_5                     4789
temp_index_1_5                4791
temp_highestgrade_1_5         4793
temp_currentgrade_1_5         4796
temp_math_score_1_5           4794
temp_english_score_1_5        4794
child_math_score_1_5          4789
child_eng_score_1_5           4789
planner_type_1_5              4789
index_1_6                     4801
temp_index_1_6                4801
temp_highestgrade_1_6         4804
temp_currentgrade_1_6         4805
temp_math_score_1_6           4804
temp_english_score_1_6        4804
child_math_score_1_6          4801
child_eng_score_1_6           4801
planner_type_1_6              4801
index_1_7                     4803
temp_index_1_7                4803
temp_highestgrade_1_7         4805
temp_currentgrade_1_7         4805
temp_math_score_1_7           4806
temp_english_score_1_7        4806
child_math_score_1_7          4803
child_eng_score_1_7           4803
planner_type_1_7              4803
index_1_8                     4805
temp_index_1_8                4805
temp_highestgrade_1_8         4805
temp_currentgrade_1_8         4805
temp_math_score_1_8           4805
temp_english_score_1_8        4805
child_math_score_1_8          4805
child_eng_score_1_8           4805
planner_type_1_8              4805
parent_index_2                4025
parent_treat_2                4025
earnings_math_pb_2            4058
earnings_nonmath_pb_2         4059
earnings_noattend_pb_2        4063
earnings_math_pg_2            4058
earnings_nonmath_pg_2         4059
earnings_noattend_pg_2        4061
occupation_math_pb_2          4032
occupation_nonmath_pb_2       4033
occupation_noattend_pb_2      4032
occupation_math_pg_2          4032
occupation_nonmath_pg_2       4033
occupation_noattend_pg_2      4034
marriage_math_pb_2            4035
marriage_nonmath_pb_2         4036
marriage_noattend_pb_2        4038
marriage_math_pg_2            4038
marriage_nonmath_pg_2         4039
marriage_noattend_pg_2        4040
children_math_pb_2            4046
children_nonmath_pb_2         4047
children_noattend_pb_2        4045
children_math_pg_2            4045
children_nonmath_pg_2         4045
children_noattend_pg_2        4044
spouse_math_pb_2              4072
spouse_nonmath_pb_2           4074
spouse_noattend_pb_2          4075
spouse_math_pg_2              4073
spouse_nonmath_pg_2           4073
spouse_noattend_pg_2          4076
math_school_p_2               4034
math_domestic_p_2             4034
boys_gifted_math_p_2          4039
boys_giftedenglish_p_2        4038
girls_domesticskills_p_2      4033
girls_parenting_p_2           4033
career_math_p_2               4034
career_english_p_2            4035
index_p_2_1                   4025
temp_index_p_2_1              4025
separate_note_p_2_1           4409
math_rank_p_2_1               4049
english_rank_p_2_1            4050
math_predict_p_2_1            4052
math_prize_p_2_1              4046
english_predict_p_2_1         4050
english_prize_p_2_1           4047
pastmathbook_cost_p_2_1       4062
pastenglishbook_cost_p_2_1    4063
pastedu_talk_p_2_1            4040
pastmath_talk_p_2_1           4042
mathbook_cost_p_2_1           4076
englishbook_cost_p_2_1        4074
math_hw_hrs_p_2_1             4077
math_hw_mins_p_2_1            4077
english_hw_hrs_p_2_1          4080
english_hw_mins_p_2_1         4080
edu_talk_p_2_1                4076
math_talk_p_2_1               4079
attend_secondary_p_2_1        4025
study_secondary_p_2_1         4103
study_secondary_p_osp_2_1        0
likely_attend_p_2_1           4049
likely_study_p_2_1            4145
likely_study_p_osp_2_1           0
index_p_2_2                   4332
temp_index_p_2_2              4338
separate_note_p_2_2           4574
math_rank_p_2_2               4344
english_rank_p_2_2            4344
math_predict_p_2_2            4346
math_prize_p_2_2              4346
english_predict_p_2_2         4347
english_prize_p_2_2           4346
pastmathbook_cost_p_2_2       4359
pastenglishbook_cost_p_2_2    4359
pastedu_talk_p_2_2            4340
pastmath_talk_p_2_2           4341
mathbook_cost_p_2_2           4360
englishbook_cost_p_2_2        4360
math_hw_hrs_p_2_2             4359
math_hw_mins_p_2_2            4358
english_hw_hrs_p_2_2          4358
english_hw_mins_p_2_2         4358
edu_talk_p_2_2                4357
math_talk_p_2_2               4357
attend_secondary_p_2_2        4332
study_secondary_p_2_2         4385
study_secondary_p_osp_2_2        0
likely_attend_p_2_2           4345
likely_study_p_2_2            4398
likely_study_p_osp_2_2           0
index_p_2_3                   4609
temp_index_p_2_3              4618
separate_note_p_2_3           4707
math_rank_p_2_3               4618
english_rank_p_2_3            4619
math_predict_p_2_3            4620
math_prize_p_2_3              4620
english_predict_p_2_3         4620
english_prize_p_2_3           4620
pastmathbook_cost_p_2_3       4622
pastenglishbook_cost_p_2_3    4622
pastedu_talk_p_2_3            4615
pastmath_talk_p_2_3           4616
mathbook_cost_p_2_3           4624
englishbook_cost_p_2_3        4625
math_hw_hrs_p_2_3             4624
math_hw_mins_p_2_3            4624
english_hw_hrs_p_2_3          4624
english_hw_mins_p_2_3         4625
edu_talk_p_2_3                4624
math_talk_p_2_3               4626
attend_secondary_p_2_3        4609
study_secondary_p_2_3         4639
study_secondary_p_osp_2_3        0
likely_attend_p_2_3           4619
likely_study_p_2_3            4645
likely_study_p_osp_2_3           0
index_p_2_4                   4734
temp_index_p_2_4              4736
separate_note_p_2_4           4764
math_rank_p_2_4               4740
english_rank_p_2_4            4740
math_predict_p_2_4            4741
math_prize_p_2_4              4741
english_predict_p_2_4         4741
english_prize_p_2_4           4743
pastmathbook_cost_p_2_4       4738
pastenglishbook_cost_p_2_4    4738
pastedu_talk_p_2_4            4739
pastmath_talk_p_2_4           4740
mathbook_cost_p_2_4           4743
englishbook_cost_p_2_4        4743
math_hw_hrs_p_2_4             4743
math_hw_mins_p_2_4            4744
english_hw_hrs_p_2_4          4744
english_hw_mins_p_2_4         4744
edu_talk_p_2_4                4744
math_talk_p_2_4               4746
attend_secondary_p_2_4        4734
study_secondary_p_2_4         4747
study_secondary_p_osp_2_4        0
likely_attend_p_2_4           4740
likely_study_p_2_4            4751
likely_study_p_osp_2_4           0
index_p_2_5                   4783
temp_index_p_2_5              4785
separate_note_p_2_5           4794
math_rank_p_2_5               4787
english_rank_p_2_5            4786
math_predict_p_2_5            4789
math_prize_p_2_5              4789
english_predict_p_2_5         4789
english_prize_p_2_5           4789
pastmathbook_cost_p_2_5       4784
pastenglishbook_cost_p_2_5    4784
pastedu_talk_p_2_5            4787
pastmath_talk_p_2_5           4788
mathbook_cost_p_2_5           4789
englishbook_cost_p_2_5        4789
math_hw_hrs_p_2_5             4789
math_hw_mins_p_2_5            4789
english_hw_hrs_p_2_5          4789
english_hw_mins_p_2_5         4789
edu_talk_p_2_5                4789
math_talk_p_2_5               4789
attend_secondary_p_2_5        4783
study_secondary_p_2_5         4791
study_secondary_p_osp_2_5        0
likely_attend_p_2_5           4788
likely_study_p_2_5            4792
likely_study_p_osp_2_5           0
index_p_2_6                   4802
temp_index_p_2_6              4802
separate_note_p_2_6           4802
math_rank_p_2_6               4802
english_rank_p_2_6            4802
math_predict_p_2_6            4804
math_prize_p_2_6              4804
english_predict_p_2_6         4804
english_prize_p_2_6           4804
pastmathbook_cost_p_2_6       4803
pastenglishbook_cost_p_2_6    4803
pastedu_talk_p_2_6            4803
pastmath_talk_p_2_6           4803
mathbook_cost_p_2_6           4804
englishbook_cost_p_2_6        4804
math_hw_hrs_p_2_6             4805
math_hw_mins_p_2_6            4805
english_hw_hrs_p_2_6          4805
english_hw_mins_p_2_6         4805
edu_talk_p_2_6                4804
math_talk_p_2_6               4805
attend_secondary_p_2_6        4802
study_secondary_p_2_6         4805
study_secondary_p_osp_2_6        0
likely_attend_p_2_6           4804
likely_study_p_2_6            4805
likely_study_p_osp_2_6           0
index_p_2_7                   4804
temp_index_p_2_7              4804
separate_note_p_2_7           4804
math_rank_p_2_7               4804
english_rank_p_2_7            4804
math_predict_p_2_7            4805
math_prize_p_2_7              4805
english_predict_p_2_7         4805
english_prize_p_2_7           4805
pastmathbook_cost_p_2_7       4805
pastenglishbook_cost_p_2_7    4805
pastedu_talk_p_2_7            4805
pastmath_talk_p_2_7           4805
mathbook_cost_p_2_7           4805
englishbook_cost_p_2_7        4805
math_hw_hrs_p_2_7             4805
math_hw_mins_p_2_7            4805
english_hw_hrs_p_2_7          4805
english_hw_mins_p_2_7         4805
edu_talk_p_2_7                4805
math_talk_p_2_7               4805
attend_secondary_p_2_7        4804
study_secondary_p_2_7         4806
study_secondary_p_osp_2_7        0
likely_attend_p_2_7           4805